In [1]:
!pip install -q pytorch-lightning datasets transformers evaluate accelerate scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 27.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 55.0 MB/s eta 0:00:00

In [3]:
# Instalacion de librerias
import random
import torch
import numpy as np
import os
from pytorch_lightning import seed_everything
import matplotlib.pyplot as plt
import seaborn as sns
import re

seed_val = 42
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)# Store the average loss after eachepoch so we can plot them.
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
os.environ["TF_DETERMINISTIC_OPS"] = "1" # See:https://github.com/NVIDIA/tensorflow-determinism#confirmed-current-gpu-specific-sources-of-non-determinism-with-solutions
seed_everything(42, workers=True)

from datasets import Dataset, DatasetDict #, load_metric EN PRINCIPIO ESTÁ DESCONTINUADO, TENDREMOS QUE BUSCAR OTRA ALTERNATIVA
import pandas as pd
import sklearn as sk
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score, f1_score
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, \
TrainingArguments, Trainer, pipeline, EarlyStoppingCallback
from huggingface_hub import login

INFO:lightning_fabric.utilities.seed:Seed set to 42

In [4]:
# Comprobación de disponibilidad de GPU
if torch.cuda.is_available():
    # Si hay una GPU disponible, la asignamos como dispositivo principal
    device = torch.device("cuda")
    print(f'✅ GPU detectada. Trabajando con: "{torch.cuda.get_device_name(0)}"')
else:
    # Si no hay GPU, el modelo y los tensores irán a la CPU
    device = torch.device("cpu")
    print('⚠️ Trabajando con CPU.')
    print('Para usar la GPU en Colab: Ve al menú superior "Entorno de ejecución" -> "Cambiar tipo de entorno de ejecución" -> Selecciona "GPU T4".')

# Opcional pero recomendado: Ver cuánta memoria VRAM tienes disponible
if device.type == 'cuda':
    memoria_total = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f'Memoria VRAM total disponible: {memoria_total:.2f} GB')

✅ GPU detectada. Trabajando con: "NVIDIA L4"
Memoria VRAM total disponible: 23.66 GB

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Entrenamiento Train/Valid/Test

## Lectura y etiquetado de Datos

In [6]:
# ================================
# 1. Carga y preparación de datos
# ================================
import pandas as pd
from sklearn.model_selection import train_test_split
# from datasets import Dataset

print("Cargando el dataset maestro de entrenamiento...")

# Hombres
#ruta = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Perspectivismo/Hombres/train_descartes.csv"
#ruta = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Perspectivismo/Hombres/train_duda_machismo.csv"
#ruta = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Perspectivismo/Hombres/train_duda_no_machismo.csv"
#ruta = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Perspectivismo/Hombres/train_unrolling.csv"

# Mujeres
#ruta = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Perspectivismo/Mujeres/train_descartes.csv"
#ruta = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Perspectivismo/Mujeres/train_duda_machismo.csv"
#ruta = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Perspectivismo/Mujeres/train_duda_no_machismo.csv"
#ruta = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Perspectivismo/Mujeres/train_unrolling.csv"

# Cargamos el TRAIN_MASTER que contiene el 80% de los datos (el test fijo ya está guardado aparte)
ruta = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/EXIST2025_training_3_1_master.csv"

df_train_master = pd.read_csv(ruta)

# Definicion de rutas para trabajar con el perspectivismo H/M

test_df = pd.read_csv('/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/EXIST2025_test_3_1.csv')

# Limpiamos el índice extra (si existe) y renombramos la columna
if "Unnamed: 0" in df_train_master.columns:
    df_train_master = df_train_master.drop(columns=["Unnamed: 0"])
df_train_master = df_train_master.rename(columns={"label_task_3_1_merged": "label"})
df_train_master["label"] = df_train_master["label"].astype(int)

if "Unnamed: 0" in test_df.columns:
    test_df = test_df.drop(columns=["Unnamed: 0"])
test_df = test_df.rename(columns={"label_task_3_1_merged": "label"})
test_df["label"] = test_df["label"].astype(int)

# División dinámica: 90% Train, 10% Validation (extraído solo del bloque maestro)
# Mantenemos random_state para que la validación sea estable entre pruebas del mismo modelo
train_df, val_df = train_test_split(df_train_master, test_size=0.10, stratify=df_train_master["label"], random_state=42)

print("Distribución fichero de entrenamiento (Train):")
print(train_df['label'].value_counts())

print("\nDistribución fichero de validación (Valid):")
print(val_df['label'].value_counts())

print("\nDistribución fichero de test (estático):")
print(test_df['label'].value_counts())

# train_dataset = Dataset.from_pandas(train_df)
# eval_dataset = Dataset.from_pandas(val_df)

# Separamos la ruta por las barras inclinadas
partes = ruta.split('/')

# Tomamos el penúltimo elemento (la carpeta)
carpeta = partes[-2]

# Tomamos el último elemento, lo separamos por el punto y nos quedamos con la primera parte
archivo = partes[-1].split('.')[0]

# Unimos todo
resultado = f"{carpeta}-{archivo}"

print("\nResultado: " + resultado)

Cargando el dataset maestro de entrenamiento...
Distribución fichero de entrenamiento (Train):
label
0    940
1    865
Name: count, dtype: int64

Distribución fichero de validación (Valid):
label
0    105
1     96
Name: count, dtype: int64

Distribución fichero de test (estático):
label
0    261
1    241
Name: count, dtype: int64

Resultado: training-EXIST2025_training_3_1_master

## Preprocesado del texto

In [7]:
# Para ver el vocabulario del dataset

import pandas as pd

# Suponiendo que la columna de texto se llama 'text'
# Tokeniza y obtiene todas las palabras
vocabulario = set(
    palabra.lower()
    for fila in df_train_master["text"].dropna()
    for palabra in fila.split()
)

# Mostrar todo el vocabulario
print(vocabulario)

# (Opcional) Ver el número de palabras únicas
print(f"\nTotal de palabras únicas: {len(vocabulario)}")

{'pintilla,', 'ojito', 'comúnmente', 'rasgo', 'obrador.', '¿soy', 'móvil,', 'pon', 'greatest', '¿estás', 'fzto', 'jugando', 'confundes.', 'angelo', 'earth', '105', 'unnecessary', 'pressure', 'assets', 'puz', 'preocupan.', 'felix', 'bone,', 'bulbs,', 'jeque,', 'oprime.', 'tomboy', '40', 'esposa,', 'supermercado.', 'verguenza', 'sister.', 'america,', 'non-self', 'cholo', 'his', 'conexión,', 'rights,', 'reasonably', 'vale,', 'rating', 'falsas.', 'repito', 'amor.', 'check_mark_button', 'cancelled', 'cago', 'held', 'constitucionalistas!', '7w', 'unió', 'plica', 'acción,', '28-year-old', 'aymanonce', 'memory', 'astray', 'comointurones?', 'dichos', 'pursuing', 'dare', 'maldito!', 'jus', 'tonta.', 'gabriel', 'negaba,', 'sé!', 'ensalada,', 'alma', '49/jsl', 'coiondas', 'h0uo', 'sale.oh', 'primaria', '[hood', 'escuchen', 'diploma', 'cans,', 'be?', 'bebe-mamá,', 'no_thinky', 'tiny', 'cima', 'barcelona', 'subo', '"we', 'vidrio', 'parió!', '{k1', 'pulpo', 'mama,', 'aubukuto', 'mes.', '206', 'pidillas', 'auténtico.', 'semaforo', 'tranquila', 'spanish?', 'papatalo', 'serious', 'men?', 'skirts,', 'seguro?', 'pinzas', '"compañere".se', 'assuming', "'30.", 'exhibir', 'miembros', 'pendejo.', 'miope,', 'dad,', 'tear', 'cuestiona', 'cansó', 'wife!', 'lift', 'steel', 'luego,', 'lelcolagos', 'luis', 'este,', '2,000', 'lwor', 'sou', 'painted', '¿sos', 'regulan,', 'immature', 'bass,', 'evitar,', 'way,', 'lifetime', 'can.', 'ocultaron', 'nudenmark', '"sí,', 'nah,', 'enteré', 'iguales.todos', 'done.', "j'.", 'crueles', 'exageran,', 'mexico,', 'sugar,', 'ponen,', 'lawyers', 'deshidratarte.', 'fighting', '$200.', 'flaps.', 'magdalena.', 'hurt', 'heteros', 'evaluar', 'pagas', 'fluttering', 'think.', 'sexual,', 'hunting', 'muchísimas', 't4nade;', 'paraada', 'instagram,', 'asqueroso?', 'articulaciones,', 'corazón.', 'endurance.', 'guest,', 'mucous', '{as', 'f-estúpida,', 'public,', 'esperar!', 'crecía', 'muñecas', 'roblox', 'foxg1.', 'hermania!', '🆁🅸🅽🅶🆄🅴́', 'spent', 'tired_face', 'relacionada', 'monotone', '¿dialogas', 'escuches.', 'viento', 'episode', 'incoherente,', '𝐭𝐚𝐛𝐮́!', 'manvan),', 'escuadra.', 'tumbler_glass', '"whitefem"', '"limpia', 'selecciona', 'catorce', 'j/iuoytenade', 'victimizarse', 'manspreading,', '203.', 'tolerancia.quiero', 'rivas', "father's", '->', 'playing,', '"woman"', 'inclusivo,', 'entró', 'religiosa.', 'pibes.', "with.i'll", 'piropos', 'ana_georgieva5', 'woman_shrugging_medium-dark_skin_tone', '5-4', '"debes', 'juli,', 'superficial,', 'front-row', 'institucional', 'jessica', 'suddenly', 'white_heart', 'guiados', '"beetles"', 'encuent', 'mi_mte', 'haibre', 'mct', 'prefer', 'culpa.el', 'activist', 'teen', 'invisibilizados', 'remember?', 'biphobic', 'nuevecita,', 'mask.', 'trans,', 'i@', 'pequeño', 'no_entry', 'avigilon', 'koga-san', 'desafío', 'segura,', 'acuerdo', 'otaku', 'certain', 'próxima.', 'den', 'koksu,', 'tiktoks', 'momma', 'wilted_flower', 'arrived.', 'migel', 'peep', 'problemadca', 'woods', '¿amiga,', 'diamantes,', 'between.', 'también.', "n'est", 'fucked', 'misinformation', '¡increíble!', 'bis', 'ai', 'both?', 'toccon', 'milei', 'enamoran', 'hidden', 'influences', 'creepy', 'comen', 'puchopocka', 'tuned', 'autorización', 'contempladas', 'voltear.', 'lavada', 'colegas', 'hardships,', 'oscuros;', 'upper', 'catedral', 'antes,', 'soak', 'tierra.¿qué', 'turned', 'genial', 'asigna', 'hubiera', 'message', 'got', 'magnitud,', 'ham', 'cobrarnos', 'amado', 'ocultar', 'gentil', 'previno', 'yupppp', 'complex.', 'enchufar', 'frágil?', 'año', 'utiliz"', 'wifi,', 'ellas?', 'english,', 'inculada,', 'conditions', '2hj', 'estaba.en', 'dre', 'fijaros', 'nosotros.', '17.', 'closet.', 'grace,', 'obós', '8i', 'pesos.', 'traumada', 'tercezxunosza', 'conducir', 'tummy', 'dejo.', 'cabeza,', 'maintain', 'marico?', 'moods,', 'aquí.', 'ver".', 'emanuel', 'mon', 'scene.', '¿hubo', 'bruegel', 'irla', 'gabigar', 'emocionales', '2026', 'andamos,', 'rapto.', 'tuyo?', 'herself', 'divulgando', 'mandaba.', 'blancas,', 'señal', 'ser,', 'aggravated', 'golpearan', 'kante.', 'monra', 'feminismo', 'deberían', 'enojar,', 'brillo', 'o2,', 'comportamientos', 'section?', 'state', 'madurez,', 'residen', 'amazon.', 'podía', 'perdiendo', 'disclaimer', 'recently,', 'rama', 'shopping', 'smithaa,', 'doler?', 'lesbian.', 'concepto', 'balón', 'pathetic', 'pasarán', 'chippi', 'yeah!', 'تملي', 'entrada,', 'z', 'give', 'jima!', 'hechas.eso', 'mother,', 'preciosoooo', 'stand-up', 'credibility', 'wey', 'favourite', 'mifri', 'u', 'hiciste?', 'haha', 'bosques,', 'libertad,', 'padreada', 'consigna', 'participation.', 'canvas', 'escuche;', 'hola', 'glowie', 'gujeres', 'kii', 'lanzan', '40080uzacreciendo', 'inflation', 'lava,', 'estado?', 'feeling.', 'importaría', 'cambiando,', 'tecnica', 'rol', 'tío.', 'todd', 'about,', 'fachera.el', 'kidding,', 'abuelita.', 'license.', 'object.', 'example"', 'animales,', 'limit', 'utilizándolo', '79998', 'rotello', '0ono', 'showroom.', 'intelectualidad', 'hella', 'república', 'disimulo.', 'peterson', 'jóvenes.', 'bunker,', 'uff,', 'dogs.', 'harassed', 'vivirlo.', 'stamp', 'b1ty!be', 'digital', 'ofender,', 'interrupciones."', 'tienes,', 'senate', 'fresa,', 'haciendo?', 'dejaré', 'yesfiktòr', 'indisciplina,', 'genial.', 'mean.', 'calvo,', 'hecha', 'excel.', 'jugo', 'gamer', 'hating', 'secretos', 'stamford', 'rip', 'nada?ese', 'corales', "'aia", '"chemin', 'dating', 'planeta', 'momos', 'aquellas', '1.', '"2,000', 'rupturas', 'naturaleza', 'marching', 'cyber', 'viralísimo', 'naming', 'ale,', 'verónica', "'0r", 'fjro', 'gente…', "asc's", 'relacionadasas', 'traviesa,', 'sanción,', 'sees', 'society.', 'pedals', 'es.ahí', '[os01', 'igualmente', 'do,', '44', 'shark.', 'elon', 'fase', 'muerte.', 'buscando', 'basilio', 'japan', 'censura', 'otrayamejorlagentelevor', 'cgcke', '"lucharé', 'mentalidad', 'vergüenza.sí', 'antelope', 'aleinadbell', 'research,', 'uñas?', 'spin', 'open', '¿recuerdan', 'diva.', 'loquita,', 'texas', 'etuan', 'turbina,', 'macarena?', 'mommy', 'guys!', 'pertenece]', 'deserves', 'twiningeface', 'oppressive', 've.', 'duermas', 'esperma', 'juguetes', 'ignore', 'apartment?', 'winner,', 'taki-taki!', '¿dijenahesustavon?', 'krok10', 'prendas', 'evidencian', 'declaró', 'cumpliendo', 'descubra', 'indígena', 'afuera.', 'vidas', 'kaende', 'weaknesses,', 'd@', 'three', 'enojado?', 'detectar', 'twerk.', 'marcar', 'capacidad', 'pcos', '282', 'cambiaba', 'belt.', 'greenup', '"¿voy', 'recoger.cuando', 'anita', 'anymore.', 'pude', 'sucede.', 'sexist.', 'autism', 'aqaszu', 'pulmón.', 'transform', 'drink', 'ganado', '@pato_hn32', 'lilith', 'offer.', 'turbondeiniel1633', 'sf', 'bromeo;', 'inequality', 'sweater.', 'conocí', 'viendo', 'exige', 'peetmontzingo', '])', 'información.', 'portarnos', 'micrófono.', 'patriarcado,', 'pillow', 'snap,', 'gracias.', 'xlh', 'gemini.', 'vh.tener', 'aumentará', 'queens', 'hijos,', 'trelew.', 'sbc', 'juzgados', 'apendejarse', 'divulgar', 'frío,', 'fantasy.', 'alejé', 'm4lvad0s",', 'quiuaba', 'yimonade', 'años.', 'ooa', 'leave', '"it', 'esóticos.en', 'analicemos,', 'caigas', 'corriente', 'aware', '333.6k', 'diez?', 'empoderarnos', 'double,', 'viéndome', 'finalidad', 'pacto', 'refri.', 'cuánta', 'bonificaciones', 'logras', 'comunistas,', 'planea', 'costaron', 'hermere,', 'todo', 'huevones', 'wanted.', 'carro', 'maternidad', 'inferiores', 'congo,', 'session', 'amabilidad', 'egreso', 'reso', 'clever.', 'drama,', 'palicta,', 'lyrics,', 'dyer.da', 'esperma.entre', 'm13rda', 'razones.la', 'millón,', 'fiscalía', 'vicente', 'toco', 'skin', '"cosas', 'amarillis.', 'ponte', 'ángel!', 'aconsejan', 'parecer', 'dream,', 'presume', 'harían', 'sra.se', 'forming', 'mare', '388', 'stuck', 'scooter?', 'refugiarse', '%b', 'tiktok’s', 'sandhu', '9-1', "isn't", 'fris', '"mom', 'ode', 'lave,', '091e2monke', 'importantes,', 'sí!', 'pronto,', '¿crees', 'mamá.todos', 'supporter.', 'pero..."', 'dejemos', 'adílyy', 'gone,', '€i-si', 'pequeñas', 'arte,', 'pivas.', '2yo', 'pm.', 'cantes', 'diferente', 'construcción', 'paisa', 'throughout', 'pezoneras', 'colgan', 'fanáticas', 'ligando', '9134j004091.', 'destacar', 'confidencial', 'turbulent,', 'chewy', 'tribu', 'lover', 'ups', 'devolución', 'respete.', 'want.', '"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""', 'taxista', 'escuela,', 'sonciento,', 'futuro,', 'realmente', 'editar', 'matthew', 'evitaban', 'prototipo', 'música)', 'already.', 'finish', 'diputada', 'irrovoronte', 'yendo', 'novi@', '14*8', 'almademia_amorconscientealmademia_amorconsciente', 'perdí.', 'puto.', '"cerdo"', '"amiga",', '(7a399iixx', 'benes', "261gu'", 'oil', 'vuclapolrecitaeokona', 'fo', 'amdenciasalazar59.', 'puerto?', '21a', 'merecen,', '`j', 'fallos', '"where', 'tango,', 'desean,', 'está,', 'dietas,', 'ass?', 'penalización', 'sales', 'presión.', 'veras', 'iktck', 'mans,', 'misoginos', 'parecer,', 'waliciagacosta.', 'falling', 'escandaliza.', 'uy!', 'pedirlo.en', 'footballers.', 'filkkrk', 'cacciewdo', 'small.', 'taxi', 'gaphgach_', 'otro,', 'world,', 'ayudarme,', 'nnrn', 'ended', 'mifepristona', 'envra', 'favor', 'salgamos!', 'office.', 'see,', '013dod', 'realidad', 'responsibilities', '#tac..', 'esparció', 'dejarse', 'piedritas', 'utmost', 'emoción!', 'afirmando', 'kids,', 'camionero,', 'sabe', 'carita.', '¿tú', 'ssssis', 'hablando', 'exposed,', 'teclado.', 'acosa', '204', 'usuario,', 'jobs', 'treating', 'aiedo;', 'quemado', "lookin'", 'despega.', 'escuelas', 'davidpaez3', 'farenlal', 'ron', 'quicio.', 'ojos', 'tontería', 'sis', 'ponyqu33n8', 'ariqarzs', 'monólogo', 'cosasza', 'acondicionado', 'aguantan.', 'apoyo,', 'pobre.', 'teniendo', 'imponen', '450', 'motherfuckers.', 'zh', 'añoramos', 'bos', 'refuerza', '"segunda', "master's", 'dino', 'discutir', 'pijama', 'laikac', 'hac', 'thankful', 'tory', 'en0s', 'boob.', 'friends,', 'petróleo.', 'appearance.', 'lxv', 'grabarlos,', 'acompañadas', 'niy', 'toalla', 'crow.', 'booty-head', 'bisexual.', 'instead', 'regresaron', 'tachkino', 'fudge!', 'suyo.', 'oiegin', 'stage', 'cambiarlo.si', 'across', 'doing."', 'vatos?', 'defies', 'alva,', 'pueblo",', 'charlie', 'healthier', 'topping', 'patricia', 'emocionaban', '¡fea!', 'vese', 'jordan', 'lum0', '0.05', '"¡hey,', 'ears', 'perú.', 'error.', 'empezaste', 'economía.argentina', 'jgbok', 'vih', 'considerarlo', 'kato', 'puck5,', 'obvious', 'parar', 'moquia,', 'menstruan.', 'beep.', 'clausura', '[1ao42', "dad's", 'escritos', 'parri_434', 'pausa,', 'ego,', 'bructi', 'vale.no', '9.05', 'awful', '"orlarok26', 'other.', 'demográfico,', 'naturales.', 'parkouretf', 'reflexionar', "5'3", 'vite', 'campo', 'máximo', 'sans', 'nina', 'enfrentas', 'molaria', 'ría,', '"luego,', 'fumar,', 'lloran,', 'violet', 'ajenas."', 'rituales', '60/60', 'mí.', 'llegue.', 'pronounce', '"ay,', 'chelsea', '//www.policia.es/_es/colabora_informar.php', 'supremacist', '(bolsillo', 'incision.', 'mueres', 'discreta.', 'lasso.', 'ha.', 'cry', 'esclavitud', 'these,', 'dibujando', 'vincula', 'usarlos', 'dami', 'a96,?', '142', 'harming', 'cristiano', 'cold', 'chamaca', '2019,', 'applied,', 'áreas', 'explicar', 'heater', 'estabais', 'regales', 'excusa.', 'yqqahiihx', 'pioblemadca', 'results', '"2', 'etnia', 'colegios', 'skinny,', 'abajo?', 'randomly,', 'dab', 'cruzaron', 'bejt', 'viral', "'pibas", 'dives.', 'whore', 'rubios', 'provida', 'sobrenaturalmente', 'manteniéndolo', 'vuelven,', 'vacays', '#story', 'obsesionado', 'desafió', 'playa', 'esperanza', 'nochevieja', 'ochenta,', 'kakasng.', 'falcaone.', 'formulas', 'recogidos', 'enfocado', 'street.', 'maggie.', "aren't", 'criminalizan', 'kill,', 'angels,', 'industriales,', 'sábado.', 'alto!', 'loaded,', 'spice.', 'giving', 'freud.siempre', 'yuo', 'microfonod', 'greeneyedleo.', 'keywords', 'patila', 'secrets.', '"gimme', ']', '3x/', 'hagamos', 'reliable.', 'canceling', 'evento.recordarles', 'butter.', 'yourfavoriteguymonke', 'qffice', 'ignorancia', 'micocho', 'dio,', 'footballers,', '1/13', 'fruta,', 'hero.', 'oprimidos', 'le', 'fa', 'anuncios', '...', 'sensibilidad.', 'genéricos', 'strangled', 'disguised_face', 'multiorgásmicas', 'perdido.', 'eoh', 'joe,', 'compatible', 'solía', 'enamorada,', 'testicles', 'musis', 'lesbian', 'abandonarte', 'contradice', 'ad(', 'nataliaguitler', 'lluvía', 'flirt', 'cluvo', 'karts', 'chime', 'afecta,', '00.08,', 'leads', 'orientation,', 'thirst', 'vibrador', 'recibido', 'jimzo;isu', '"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""', 'unfortunately', '"covid",', 'shes', 'buscado', 'económica', 'formuleroantifem', 'vikingo,', "41)['1al51y", 'wow', 'lvk', 'ot', 'tapones', 'grasos', 'ofensivos', 'cligugeñeerez', 'todd.', 'remite', 'nuestro', 'económico', 'ui844210', 'embargo;', 'night!', 'sights', 'dedo', 'gender', 'upstairs,', 'becomes', 'mndain', 'unwavering', 'nathan,', 'recomiéndame', 'apar', 'reading', 'bullshit.', '"compañero".', 'industria,', 'ronchmarin,', '{ff-(s', 'queef', 'freund', 'canty,', 'festivales', 'desayunar', '#advicetoyourself.', 'passed', 'cinco,', '^01', 'marihuana', 'oulhul', 'goals', 'abb.y', 'harass?', 'restricts', 'chelyvaldes', 'fiesta.', 'teaching,', 'distort', 'blues).', 'dying', 'golosales,', 'cuádruple', 'muyato', 'idiot"!', 'bra,', 'requieren', 'gané.', 'it."', 'atento.¿', 'indirectas.el', 'uerte', 'all!!', 'querido.', '40@', 'baaol', 'pretende.', 'manejo', 'extraordinarily', 'locas?', 'tiño', 'pool', 'facebook', 'brecha', 'rio', 'provocadora.', 'kojn', 'excelente,', 'quiet.', 'daré', 'like,', 'victim,', 'rude', 'saltarla', 'comodidad.', 'story.', 'marsela', 'bapan', 'collins', 'looking', 'cosas.son', 'sabremos?', 'ciscoloaavanadie', 'beach_with_umbrella', 'variadas.', '8n', 'actions.', 'domínguez', 'fútbol,', '1ov{', 'kldam', 'bounce,', 'rovuronto', 'ealq', 'extranjero', '88l', 'bella', 'locations', 'name', 'spiders?', 'inocente?', 'activando', 'lecture', 'polera', 'nicki', 'cenar?', 'ready,', 'báilele', 'mental,', 'slbtkitoyo', "you've", '1gi', '€22', 'accessed', 'trae', 'comdaquddoj', 'bestie,', 'suelo.', 'victimae', 'brevemente,', 'tarjetas.', 'ocultas.', 'pican', 'significativa,', 'men”', 'enado', 'marzo.', 'judo', '(ual6mé', 'volver?', 'comenzan', 'aventuras.', '1', 'client,', 'brujerías', 'juzga', 'stay.', 'innocent', 'raped', 'characterized', 'tanto', 'compañera', 'hearts', 'agas?uj', 'página', 'tobyonthetele', 'liipstwiiitch', 'pita!', '15’s', 'commercials', 'decistís', 'flight', 'testarudo,', 'onyki,', 'ferocidad', 'dieta', 'pornstars', 'excusa', 'stranger', 'lorente,', 'cometa,', 'tired,', 'applies', 'imaginar', '"greeicy', "'carlosgms24", 'flattering', 'amarillistas"', 'tóxica.', 'certeza.', 'produjo', 'género.', 'sientes', 'alexfilmsstuff', 'verso', 'alfa,', 'ymbro', '"esa', 'trusted', 'unirme', 'silo', '193302,', '2274', '#ovibihj', 'tirando', 'niegan', 'sano', 'aristóteles', 'encantaría!', 'mansplaining', 'wow.', 'sociedad.', 'demás.se', 'queriéndola', 'bird.', "'dor9o", 'email', 'invis', 'programa.', 'relajar', 'intercambiar', 'misóginos', 'preocupé', 'wiener.', 'sky', 'alimentaria.', '.ftbl219dyl.itbl219', 'confunde,', 'colors', 'luke,', 'diversidad,', 'duela,', 'format', 'ezeidesaw', 'veintiocho,', 'cecieroo', 'quitas.', 'tells', 'guion', 'carro.', 'wattpad', 'violadores.', 'hola!', 'gallina', 'testosterone,', '4-3', 'biografía.', 'then!', 'buenorra?', 'parkourwtt', 'gratuitamente', 'necesitamos', 'manera,', 'feminista,', 'waka', '5@', 'exagerada",', 'galletas,', 'alabama', 'squids.', 'satisfacer,', 'verdades.', 'sindicato', 'infringe', 'quejan', 'evangelical,', 'innocence,', 'treatment', 'hate', "can't.", 'jesus!', 'name?', 'quitar,', 'bdjøb."', 'но', 'fandom,', 'rendir', 'robbery', 'pr', 'vfxgi', 'viste,', 'planning.', 'fantasies.', 'salvarse?', 'de,', 'ua', 'queso', 'privilegios', 'sentido."', "'eesnu'", 'ticks', 'soñar', 'federación', "''omg''", 'ramos', 'self-care', 'camara', 'valuable', 'despertar.', '¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡������������������������������������������������la', 'extraño', 'grip', 'zachmazer', 'historia.', 'buenasminits', 'imposible', 'vodka.', '¡está', 'descansar', 'sometimes', 'expanded,', 'dej', 'chloearnoldtaos.', 'baby,', 'chinor', 'ak-47', 'buscando,', 'redes,', 'nueve', 'ot-p-8-f-a-2-"-e5', 'i7u.', 'buscó"', 'adult', 'caught', 'cárcel,', 'cansado', 'care?', 'sea.', '&ff', 'coma', 'básquetbol.las', 'aaa!y', 'jut4m', 'atari', 'enferma,', 'secreta', 'veces', 'feo.wild', 'peace.', 'authentic', 'money-mouth_face', 'pasar,', 'frustración,', '"daniel_arba', 'suyas?', 'obstáculos', 'anti-mask.', 'relación', 'protest', 'enemiga.', 'look,', 'vergüenza?', 'compartimos', 'average.', 'csn', 'matate.', 'maestra', '#525*2es', 'safe', '808', 'incompetence?”', 'charlando', 'gawk', 'ensure', 'on,', 'off?', 'in?', 'bolsillos', 'crecimiento', '"philanthropy', 'sheryly', '"el', 'himno.', 'jurisdicc.', '805', 'close', 'las...', '"canción', 'vibrador.', 'chato,', 'convencimiento,', 'band-aids.', 'voluntaria', 'happens.', '1960.', 'pesas', 'away?all', 'bebes.', 'banecuador', 'como,', 'middle-aged', 'niñxs', 'bonitos', 'omitiste', 'muéstrame', 'talibán.', 'magna', '0h.', 'industria', 'j/', 'cobrar', 'away,', 'insoportable', 'seductress', 'contradicciones', 'interés', 'grizzdy', 'candidato', 'ugly', 'acaso', 'uaao14i', 'child?', '3856', 'movies', 'rub', 'recuéstate', 'por', 'hurtfuls.', 'quanimma', 'iamador', 'definitely".', 'visibly', 'experiencia', 'contestarles,', 'asian', 'zurda', 'acordas', 'atwood', 'smacks', 'pt1', 'gauge', 'incomodo.', '386', '0oomobile', '1951,', 'contesta', 'naranja', 'american?', 'bíceps', 'airpods', 'vende', 'snake?', 'convo', 'music', 'beer.', '5887.', 'mundo.las', 'parada', 'continuación*."', 'estacionar.', 'rompamos', 'confunde', 'chava', 'pedo', 'macho', 'sostenerla', '"they', 'sucks,', 'quién', '#vs', 'treated', 'entrada', 'cadenas,', 'reliable?', 'aceite', 'diablo', 'veintiocho', 'opresor', 'especial,', 'llevo.', 'lealtad?', 'valor"', 'wasn’t', '118779hixi', 'ingredients', '234400-0944', 'railroad.', 'borrar', 'coordinar', '¿provincia', 'negociar.', 'currently,', 'luis251233ix', '~hazje', '#igbt', 'j18o8nadie', 'growth.', '"watch', 'relaciones', 'esperamos', 'xxxi', 'saliendo', 'tan.', 'petrosino', 'meters.', 'sé.', 'iedo', 'historias.', 'creer.ambos', 'jt;s', 'amenazó', 'peoples', 'morally', 'enojo', 'error,', 'significativo', 'feminista"', 'brother', 'sprinkle', 'kaon', 'pueblo!¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡������������������������������������������', 'rebuild', 'hostigamiento', 'desquitas', 'enge', 'lim', 'qqu', 'último!', 'jesús!', 'whatsoever', 'platos.', 'nada.marzo,', '2grcch', 'creyendo!!,', "client's", 'might', 'promueve', 'rescatamos,', 'birth', 'david', 'challenge.el', 'screamed', '(be', 'penas.', 'changing', 'platos,', 'bold', '279090', 'bay', '3oz.', 'competir,', 'jajajajajjajajajajajaj', 'leo', 'ochn40', 'acéptenlo', 'shurfan', 'normalizar', 'pr0blema,', 'jr78kd?', "boss@'", 'hacks', 'sexuales', 'escapes.', 'energética', 'agrada.', 'latinx', 'nancy_galvezcacciedo', 'hand_with_fingers_splayed', 'fit', '74p.', 'habitantes,', "'42", "geht's.", 'bottom', 'fidelidad', 'alondritta', 'jnomtimc', 'liberac

In [8]:
import re

def remove_links(tweet):
    """Takes a string and removes web links from it"""
    tweet = re.sub(r'http\S+', '', tweet)        # remove http links
    tweet = re.sub(r'bit.ly/\S+', '', tweet)     # remove bitly links
    tweet = re.sub(r'\[link\]', '', tweet )      # remove [link]
    tweet = re.sub(r'\[url\]', '', tweet )       # remove [url]
    tweet = re.sub(r'pic.twitter\S+','', tweet)
    return tweet

def remove_users(tweet):
    """Takes a string and removes retweet and @user information"""
    tweet = re.sub('(RT\s@[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)  # remove re-tweet
    tweet = re.sub('(@[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)      # remove tweeted at
    tweet = re.sub(r'\[user\]', '', tweet )                      # remove [user]
    return tweet

def remove_hashtags(tweet):
    """Takes a string and removes any hash tags"""
    tweet = re.sub('(#[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)      # remove hash tags
    return tweet

def remove_av(tweet):
    """Takes a string and removes AUDIO/VIDEO tags or labels"""
    tweet = re.sub('VIDEO:', '', tweet)  # remove 'VIDEO:' from start of tweet
    tweet = re.sub('AUDIO:', '', tweet)  # remove 'AUDIO:' from start of tweet
    return tweet

def remove_emojis(tweet):
    emoj = re.compile("["
        u"\U00002700-\U000027BF"  # Dingbats
        u"\U0001F600-\U0001F64F"  # Emoticons
        u"\U00002600-\U000026FF"  # Miscellaneous Symbols
        u"\U0001F300-\U0001F5FF"  # Miscellaneous Symbols And Pictographs
        u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        u"\U00010000-\U0010FFFF"
        u"\U0001F680-\U0001F6FF"  # Transport and Map Symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642"
        u"\u2600-\u2B55"
        u"\ufe0f"  # dingbats

                      "]+", re.UNICODE)
    return re.sub(emoj, '', tweet)

<>:14: SyntaxWarning: invalid escape sequence '\s'
<>:14: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_1035/1710960392.py:14: SyntaxWarning: invalid escape sequence '\s'
  tweet = re.sub('(RT\s@[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)  # remove re-tweet

Convertimos todo a minúsculas

In [9]:
campo_texto = 'text'

train_df[campo_texto] = train_df[campo_texto].str.lower()
val_df[campo_texto] = val_df[campo_texto].str.lower()
test_df[campo_texto] = test_df[campo_texto].str.lower()

## Definición de métricas

In [10]:
# Función para realizar distintas métricas en ejecución

def compute_metrics(eval_pred):

  ##############
  ## predictions son logits, que son tuplas de la forma [valor1, valor2]
  ## Por ejemplo [-1.5606991,  1.6122842] significa que ha predicho eso para un documento
  ## Eso es lo que pasa a la última capa del transformer (softmax si es binario)
  ## Por eso se utiliza el índice del valor máximo de la tupla, para decir que esa es la clase que predice

  ## label_ids = [0, 1, 1, 0, 1]  # Etiquetas reales
  ## predictions = [
  ##  [0.8, 0.2],  # Predicciones para la primera instancia
  ##  [0.3, 0.7],  # Predicciones para la segunda instancia
  ##  [0.1, 0.9],  # Predicciones para la tercera instancia
  ##  [0.9, 0.1],  # Predicciones para la cuarta instancia
  ##  [0.4, 0.6],  # Predicciones para la quinta instancia
  ##           ]

  ##############

  labels = eval_pred.label_ids
  preds = eval_pred.predictions.argmax(-1)

  # Compute precision, recall, F1-score, and support
  precision, recall, f1, _ = sk.metrics.precision_recall_fscore_support(labels, preds, average="macro")

  # Calculate F1-score for the minority class (label = 1)
  f1_minoritaria= f1_score(labels, preds, pos_label=1)

  # Calculate F1-score for the majority class (label = 0)
  f1_mayoritaria = f1_score(labels, preds, pos_label=0)

  # Calculate accuracy
  acc = sk.metrics.accuracy_score(labels, preds)

  # Calculate Area Under the Curve (AUC)
  AUC = roc_auc_score(labels, preds)

  # Calculate Precision-Recall Area Under the Curve (AUC)
  PREC_REC = average_precision_score(labels, preds)

  return {
      'accuracy': acc,
      'f1': f1,
      'precision': precision,
      'recall': recall,
      'AUC': AUC,
      'f1_minoritaria': f1_minoritaria,
      'f1_mayoritaria': f1_mayoritaria,
      'PREC_REC': PREC_REC
  }

## Entrenamiento del modelo

In [11]:
# Cargamos el token de HuggingFace que lo tenemos en un fichero oculto e iniciamos sesión

#with open("/home/adrian/Escritorio/DeepSexist/DatasetManagement/EXIST2025DatasetV0.3/huggingfaceToken.txt", "r") as file:
#    hf_token = file.read().strip()

from huggingface_hub import login
from google.colab import userdata

hf_token = userdata.get('HF_TOKEN')

login(token=hf_token)
print("Login completado con éxito")

# ruta_archivo = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/token_hf.txt'

# try:
#     # Abrimos el archivo en modo lectura ('r)
#     with open(ruta_archivo, 'r') as file:
#         hf_token = file.read().strip()

#         # Hacemos el login
#         login(token=hf_token)
#         print("Login completado con éxito")
# except:
#     print("Error: No se ha encontrado el archivo " + ruta_archivo + " en la ruta especificada")

Login completado con éxito

In [12]:
# Elección del modelo

model_checkpoint = 'FacebookAI/roberta-base'

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [13]:
# Se carga el modelo preentrenado
n_labels = 2

# El uso de una función de inicialización facilita la repetición del entrenamiento
# Se puede usar la misma función de inicialización en diferentes ejecuciones del código o en configuraciones de entrenamiento diferentes
# Esto facilita la repetición del entrenamiento y la reproducibilidad, ya que se puede inicializar el modelo
# de la misma manera en cada ejecución.

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(model_checkpoint,
                                                              num_labels = n_labels) #, return_dict = True )
                                                              # use_auth_token = 'token propio de HugginFace')

In [14]:
# Para saber el nombre del modelo
model_name = model_checkpoint.split("/")[-1]
model_name

'roberta-base'

## Fine-tuning

In [15]:
# Selección de hiperparámetros
#BATCH_SIZE = 32
BATCH_SIZE = 16
NUM_TRAIN_EPOCHS = 15
#LEARNING_RATE = 3e-5
LEARNING_RATE = 1e-5
MAX_LENGTH = 128
WEIGHT_DECAY = 0.1

In [16]:


def tokenize_data(examples):
  return tokenizer(examples[campo_texto], truncation=True, max_length=MAX_LENGTH, padding=True)

In [17]:
from transformers import Trainer, TrainingArguments

optim = ["adamw_hf", "adamw_torch", "adamw_apex_fused", "adafactor", "adamw_torch_xla"]

training_args = TrainingArguments(
    output_dir = 'results',
    num_train_epochs = NUM_TRAIN_EPOCHS,
    learning_rate = LEARNING_RATE,
    per_device_train_batch_size = BATCH_SIZE,
    per_device_eval_batch_size = BATCH_SIZE,
    load_best_model_at_end = True,
    metric_for_best_model = 'f1', # Cambiar la metrica por la que queremos ajustar
    weight_decay = WEIGHT_DECAY,
    eval_strategy = 'epoch',
    save_strategy = 'epoch',
    save_total_limit = 3,
    optim = optim[1],
    push_to_hub = False,
    greater_is_better = True,
    logging_strategy = 'epoch'
)

output_dir = '/home/adrian/Escritorio/DeepSexist/TrainingBooks/Task3.1/Research/ModelosTransformers'
#output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Perspectivismo/' + resultado

# Entrenamiento de cada modelo por separado
model_output_dir = f"{output_dir}/modelo_{model_checkpoint}"

# Convierte directamente los DataFrames de Pandas a Datasets de Hugging Face
train_dataset = Dataset.from_pandas(train_df)
valid_dataset = Dataset.from_pandas(val_df)

# Reseteamos el formato para que no haya fallos
train_dataset.reset_format()
valid_dataset.reset_format()

# Obtenemos los nombres de todas las columnas originales
columns_train = train_dataset.column_names
columns_valid = valid_dataset.column_names

#Protegemos la columna "label" para no eliminarla accidentalmente

columna_etiqueta = "label" if "label" in columns_train else "labels"

if columna_etiqueta in columns_train:
    columns_train.remove(columna_etiqueta)
if columna_etiqueta in columns_valid:
    columns_valid.remove(columna_etiqueta)

encoded_train_dataset = train_dataset.map(tokenize_data, batched=True, remove_columns=columns_train)
encoded_valid_dataset = valid_dataset.map(tokenize_data, batched=True, remove_columns=columns_valid)

# Redefinimos model_init aquí para aplicar la congelación (Layer Freezing)
# def model_init():
#     # 1. Cargamos el modelo base
#     model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)
#     # 2. Congelamos todas las capas base (el "cerebro")
#     for param in model.base_model.parameters():
#         param.requires_grad = False
#     # El classifier sigue estando activo por defecto
#     return model

# Descongelación parcial de las últimas 3 capas

# def model_init():
#     # 1. Cargamos el modelo base
#     model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)

#     # 2. Congelamos TODO el cerebro base por defecto
#     for param in model.base_model.parameters():
#         param.requires_grad = False

#     # 3. Buscamos dónde guarda el modelo sus capas (esto varía según el modelo que estemos trabajando)
#     if hasattr(model.base_model, 'encoder') and hasattr(model.base_model.encoder, 'layer'):
#         capas_transformers = model.base_model.encoder.layer
#     elif hasattr(model.base_model, 'layers'):
#         capas_transformers = model.base_model.layers
#     else:
#         print("No se encontró la estructura de capas estándar. Se entrenará solo con la cabeza.")
#         capas_transformers=[]

#     # 4. Descongelamos solo las últimas 3 capas para que se adapten al vocabulario (TikTok)
#     capas_a_descongelar = 3
#     if len(capas_transformers) >= capas_a_descongelar:
#         print("Descongelando las últimas " + str(capas_a_descongelar) + " capas de un total de " + str(len(capas_transformers)))
#         for capa in capas_transformers[-capas_a_descongelar:]:
#             for param in capa.parameters():
#                 param.requires_grad = True
#     return model

# Inicializa el entrenador
trainer = Trainer(
    model_init = model_init,
    args=training_args,
    compute_metrics = compute_metrics,
    train_dataset=encoded_train_dataset,
    eval_dataset=encoded_valid_dataset,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
    processing_class=tokenizer,
)

# Entrena el modelo
trainer.train()

# Guarda el modelo entrenado
trainer.save_model(model_output_dir)

Map:   0%|          | 0/1805 [00:00<?, ? examples/s]

Map:   0%|          | 0/201 [00:00<?, ? examples/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  499MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## Resultados contra fichero de Test

In [18]:
import torch
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [19]:
# Comprobación de disponibilidad de GPU
if torch.cuda.is_available():
    # Si hay una GPU disponible, la asignamos como dispositivo principal
    device = torch.device("cuda")
    print(f'✅ GPU detectada. Trabajando con: "{torch.cuda.get_device_name(0)}"')
else:
    # Si no hay GPU, el modelo y los tensores irán a la CPU
    device = torch.device("cpu")
    print('⚠️ Trabajando con CPU.')
    print('Para usar la GPU en Colab: Ve al menú superior "Entorno de ejecución" -> "Cambiar tipo de entorno de ejecución" -> Selecciona "GPU T4".')

# Opcional pero recomendado: Ver cuánta memoria VRAM tienes disponible
if device.type == 'cuda':
    memoria_total = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f'Memoria VRAM total disponible: {memoria_total:.2f} GB')

✅ GPU detectada. Trabajando con: "NVIDIA L4"
Memoria VRAM total disponible: 23.66 GB

### 1. Carga del mejor modelo desde drive

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
test_df = pd.read_csv('/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/EXIST2025_test_3_1.csv')

# Limpiamos el índice extra (si existe) y renombramos la columna
if "Unnamed: 0" in test_df.columns:
    test_df = test_df.drop(columns=["Unnamed: 0"])
test_df = test_df.rename(columns={"label_task_3_1_merged": "label"})
test_df["label"] = test_df["label"].astype(int)

campo_texto = 'text'
test_df[campo_texto] = test_df[campo_texto].str.lower()

In [21]:
model_checkpoint = 'FacebookAI/roberta-base'
model_name = model_checkpoint.split("/")[-1]

output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/' + model_name
#output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Perspectivismo/' + resultado


# Entrenamiento de cada modelo por separado
model_output_dir = f"{output_dir}/modelo_{model_checkpoint}"

print(f"Cargando tokenizador y mejor modelo desde: {model_output_dir}")
tokenizer_test = AutoTokenizer.from_pretrained(model_output_dir)
model_test = AutoModelForSequenceClassification.from_pretrained(model_output_dir).to(device)
model_test.eval()

Cargando tokenizador y mejor modelo desde: /content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/roberta-base/modelo_FacebookAI/roberta-base

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=2, bias=True)
  )
)

### 2. Predicciones sobre el conjunto de test fijo

In [22]:
predicciones = []
y_true = test_df['label'].tolist()
y_pred = []

for index, row in tqdm(test_df.iterrows(), total=len(test_df), desc=f"Inferencia en Test ({model_name})"):
    # Usamos la variable campo_texto que definiste antes
    texto = str(row[campo_texto])

    # Tokenización
    inputs = tokenizer_test(texto, return_tensors="pt", padding=True, truncation=True, max_length=128).to(device)

    with torch.no_grad():
        outputs = model_test(**inputs)
        # Softmax para obtener la probabilidad de la clase 1 (Misógino)
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]
        prob_misogino = probs[1].item()

    predicciones.append({
        "id_EXIST": row["id_EXIST"],
        "prob_texto": prob_misogino
    })

    # Decisión binaria (Umbral 0.5)
    y_pred.append(1 if prob_misogino > 0.5 else 0)

Inferencia en Test (roberta-base): 100%|██████████| 502/502 [00:04<00:00, 103.19it/s]

### 3. Resultados oficiales y métricas

In [23]:
print("\n" + "="*50)
print(f"🏆 RESULTADOS OFICIALES EN TEST FIJO: {model_name} con el dataset {resultado} ")
print("="*50)
print(f"F1-Score (Macro): {f1_score(y_true, y_pred, average='macro'):.4f}")
print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")
print("\nMatriz de Confusión:\n", confusion_matrix(y_true, y_pred))
print("\nClassification Report:\n", classification_report(y_true, y_pred, target_names=["No Misógino", "Misógino"]))

==================================================
🏆 RESULTADOS OFICIALES EN TEST FIJO: roberta-base con el dataset training-EXIST2025_training_3_1_master
==================================================
F1-Score (Macro): 0.6934
Accuracy: 0.6972

Matriz de Confusión:
 [[203  58]
 [ 94 147]]

Classification Report:
               precision    recall  f1-score   support

 No Misógino       0.68      0.78      0.73       261
    Misógino       0.72      0.61      0.66       241

    accuracy                           0.70       502
   macro avg       0.70      0.69      0.69       502
weighted avg       0.70      0.70      0.69       502

### 4. Guardado del CSV para futuro ensemble

In [24]:
ruta_guardado = f"{output_dir}/predicciones_test_{model_name}.csv"
pd.DataFrame(predicciones).to_csv(ruta_guardado, index=False)
print(f"\n✅ Archivo CSV de predicciones guardado en: {ruta_guardado}")

✅ Archivo CSV de predicciones guardado en: /content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/roberta-base/predicciones_test_roberta-base.csv

# Optimización de hiperparámetros

Esto lo hacemos porque ha sido el modelo *Transformer* de entre multilingüe, español e inglés que mejor nos ha funcionado.

In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 27.8 MB/s eta 0:00:00
Downloading alembic-1.18.5-py3-none-any.whl (264 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.7/264.7 kB 28.8 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.18.5 colorlog-6.12.0 optuna-4.9.0

In [ ]:
import optuna
from transformers import Trainer, TrainingArguments, AutoModelForSequenceClassification, EarlyStoppingCallback

model_checkpoint = 'FacebookAI/roberta-base'
n_labels = 2

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)

In [ ]:
def optuna_hp_space(trial):
    return {
        # 1. Learning Rate (Tasa de aprendizaje)
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True),

        # 2. Weight Decay (Penalización contra el sobreajuste)
        "weight_decay": trial.suggest_float("weight_decay", 0.01, 0.1),

        # 3. Warmup Ratio (Calentamiento inicial para no destruir pesos pre-entrenados)
        "warmup_ratio": trial.suggest_float("warmup_ratio", 0.0, 0.1),

        # 4. Batch Size
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [8, 16]),

        # 5. Planificador de la Tasa de Aprendizaje (Linear vs Cosine)
        "lr_scheduler_type": trial.suggest_categorical("lr_scheduler_type", ["linear", "cosine"]),

        # 6. Recorte de Gradientes (Estabilidad en el entrenamiento)
        "max_grad_norm": trial.suggest_float("max_grad_norm", 0.5, 2.0)
    }

In [ ]:
training_args = TrainingArguments(
    output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/Optuna/roberta-base',
    num_train_epochs = 10,           # Lo capamos a 5 épocas por intento para que la búsqueda sea rápida
    eval_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True,
    metric_for_best_model = 'eval_f1',   # Apuntamos a tu métrica
    greater_is_better = True,
    fp16 = True,                    # Compresión activada para que Colab vuele
    push_to_hub = False,
    logging_strategy = 'epoch',
    report_to ="none",
    disable_tqdm = False            # Para ver la barrita de progreso
)

In [ ]:
trainer = Trainer(
    model_init = model_init,
    args = training_args,
    compute_metrics = compute_metrics,
    train_dataset = encoded_train_dataset,
    eval_dataset = encoded_valid_dataset,
    processing_class = tokenizer,
    # Tolerancia cero: si en 2 épocas no mejora, aborta el intento y pasa al siguiente
    callbacks = [EarlyStoppingCallback(early_stopping_patience=2)]
)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
print("🔍 Iniciando rastreo bayesiano de hiperparámetros con Optuna...")

best_trial = trainer.hyperparameter_search(
    direction = "maximize",                    # Queremos el número más alto posible
    backend = "optuna",                        # Motor de búsqueda
    hp_space = optuna_hp_space,                # Nuestra función de límites
    n_trials = 20,                             # Va a hacer 20 intentos (aprox 1.5 - 2 horas)
    pruner=optuna.pruners.MedianPruner(n_startup_trials=2, n_warmup_steps=1),
    compute_objective = lambda metrics: metrics["eval_f1"] # El objetivo es maximizar tu eval_f1
)

[I 2026-07-24 19:19:52,326] A new study created in memory with name: no-name-1d7fc227-ca90-4684-803f-802af30004f6

🔍 Iniciando rastreo bayesiano de hiperparámetros con Optuna...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:22:59,175] Trial 0 finished with value: 0.6911677240285488 and parameters: {'learning_rate': 4.1282982481291265e-05, 'weight_decay': 0.04141148439605289, 'warmup_ratio': 0.07398408175670355, 'per_device_train_batch_size': 16, 'lr_scheduler_type': 'cosine', 'max_grad_norm': 0.7013989367637372}. Best is trial 0 with value: 0.6911677240285488.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:27:08,181] Trial 1 finished with value: 0.6130846728831779 and parameters: {'learning_rate': 3.156137678314488e-05, 'weight_decay': 0.06153146664299751, 'warmup_ratio': 0.0030155712044452557, 'per_device_train_batch_size': 16, 'lr_scheduler_type': 'linear', 'max_grad_norm': 1.9523607423806197}. Best is trial 0 with value: 0.6911677240285488.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:28:17,058] Trial 2 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2026-07-24 19:28:40,438] Trial 3 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2026-07-24 19:29:01,658] Trial 4 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-07-24 19:29:16,675] Trial 5 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2026-07-24 19:29:36,443] Trial 6 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-07-24 19:29:55,830] Trial 7 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2026-07-24 19:30:15,461] Trial 8 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:31:00,291] Trial 9 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:31:45,107] Trial 10 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:33:34,536] Trial 11 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-07-24 19:33:53,109] Trial 12 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:35:28,491] Trial 13 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:37:26,895] Trial 14 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:39:11,229] Trial 15 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2026-07-24 19:39:30,127] Trial 16 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:41:01,989] Trial 17 finished with value: 0.6702173309437868 and parameters: {'learning_rate': 2.8376386503335898e-05, 'weight_decay': 0.04696667873853187, 'warmup_ratio': 0.09981480970221145, 'per_device_train_batch_size': 16, 'lr_scheduler_type': 'cosine', 'max_grad_norm': 0.7481155346981706}. Best is trial 0 with value: 0.6911677240285488.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:42:34,962] Trial 18 finished with value: 0.6915346534653465 and parameters: {'learning_rate': 1.9969139895549522e-05, 'weight_decay': 0.04577665981332442, 'warmup_ratio': 0.09735399366470507, 'per_device_train_batch_size': 16, 'lr_scheduler_type': 'cosine', 'max_grad_norm': 0.7518646670911172}. Best is trial 18 with value: 0.6915346534653465.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-24 19:45:36,023] Trial 19 finished with value: 0.6702624776297474 and parameters: {'learning_rate': 1.8674329378029044e-05, 'weight_decay': 0.02768051216646101, 'warmup_ratio': 0.08838205751557081, 'per_device_train_batch_size': 16, 'lr_scheduler_type': 'cosine', 'max_grad_norm': 0.9264415504446655}. Best is trial 18 with value: 0.6915346534653465.

In [ ]:
print("\n" + "="*50)
print("🚀 ¡BÚSQUEDA TERMINADA! 🚀")
print(f"🏆 El mejor F1 conseguido ha sido: {best_trial.objective}")
print(f"⚙️ Los hiperparámetros ganadores son:")
for key, value in best_trial.hyperparameters.items():
    print(f"   - {key}: {value}")
print("="*50)

==================================================
🚀 ¡BÚSQUEDA TERMINADA! 🚀
🏆 El mejor F1 conseguido ha sido: 0.6915346534653465
⚙️ Los hiperparámetros ganadores son:
   - learning_rate: 1.9969139895549522e-05
   - weight_decay: 0.04577665981332442
   - warmup_ratio: 0.09735399366470507
   - per_device_train_batch_size: 16
   - lr_scheduler_type: cosine
   - max_grad_norm: 0.7518646670911172
==================================================

# Entrenamiento del modelo después de la optimización de hiperparámetros

In [ ]:
from transformers import Trainer, TrainingArguments, AutoModelForSequenceClassification, EarlyStoppingCallback
from datasets import Dataset

In [ ]:
# 1. Configuración del modelo
model_checkpoint = 'FacebookAI/roberta-base'
n_labels = 2

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)

In [ ]:
# 2. Las Constantes Ganadoras de la Optimización con Optuna
BATCH_SIZE = 16
NUM_TRAIN_EPOCHS = 10       # Le damos margen completo para buscar su verdadero pico
LEARNING_RATE = 1.9969139895549522e-05  # La tasa de aprendizaje perfecta descubierta
WEIGHT_DECAY = 0.04577665981332442      # Regularización fuerte anti-overfitting
WARMUP_RATIO = 0.09735399366470507      # Calentamiento lineal de gradientes
LR_SCHEDULER_TYPE = "cosine"
MAX_GRAD_NORM = 0.7518646670911172

optim = ["adamw_hf", "adamw_torch", "adamw_apex_fused", "adafactor", "adamw_torch_xla"]

In [ ]:
# 3. Rutas automáticas a tu Google Drive Principal
output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/RoBERTa-base_Optimizado'
model_output_dir = f"{output_dir}/modelo_final_tfm"

training_args = TrainingArguments(
    output_dir = output_dir,
    num_train_epochs = NUM_TRAIN_EPOCHS,
    learning_rate = LEARNING_RATE,
    per_device_train_batch_size = BATCH_SIZE,
    per_device_eval_batch_size = BATCH_SIZE,
    load_best_model_at_end = True,
    metric_for_best_model = 'f1',
    weight_decay = WEIGHT_DECAY,
    warmup_ratio = WARMUP_RATIO,     # <-- Inyectamos el Warmup ratio ganador
    eval_strategy = 'epoch',
    save_strategy = 'epoch',
    save_total_limit = 2,
    optim = optim[1],                # adamw_torch estable
    fp16 = True,                     # Compresión en GPU activa para máxima velocidad
    push_to_hub = False,
    greater_is_better = True,
    logging_strategy = 'epoch',
    lr_scheduler_type = LR_SCHEDULER_TYPE,
    max_grad_norm = MAX_GRAD_NORM,   # <-- Inyectamos el Max Grad Norm ganador
)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

In [ ]:
model_checkpoint = 'FacebookAI/roberta-base'

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

In [ ]:
# 4. Preparación de Datasets (Conversión limpia de tus DataFrames de Pandas)
train_dataset = Dataset.from_pandas(train_df)
valid_dataset = Dataset.from_pandas(val_df)

train_dataset.reset_format()
valid_dataset.reset_format()

columns_train = train_dataset.column_names
columns_valid = valid_dataset.column_names

columna_etiqueta = "label" if "label" in columns_train else "labels"

if columna_etiqueta in columns_train:
    columns_train.remove(columna_etiqueta)
if columna_etiqueta in columns_valid:
    columns_valid.remove(columna_etiqueta)

encoded_train_dataset = train_dataset.map(tokenize_data, batched=True, remove_columns=columns_train)
encoded_valid_dataset = valid_dataset.map(tokenize_data, batched=True, remove_columns=columns_valid)

Map:   0%|          | 0/1805 [00:00<?, ? examples/s]

Map:   0%|          | 0/201 [00:00<?, ? examples/s]

In [ ]:
# 5. Inicialización del Entrenador de Producción
trainer = Trainer(
    model_init = model_init,
    args = training_args,
    compute_metrics = compute_metrics,
    train_dataset = encoded_train_dataset,
    eval_dataset = encoded_valid_dataset,
    callbacks = [EarlyStoppingCallback(early_stopping_patience=3)], # Margen de 3 épocas sin mejorar para parar
    processing_class = tokenizer,
)

print("Lanzando el entrenamiento definitivo de roBERTa-base con los mejores hiperparámetros...")
trainer.train()

model.safetensors: reconstructing file:   0%|          |  0.00B /  499MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Lanzando el entrenamiento definitivo de roBERTa-base con los mejores hiperparámetros...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=791, training_loss=0.4341429313727185, metrics={'train_runtime': 245.8805, 'train_samples_per_second': 73.41, 'train_steps_per_second': 4.596, 'total_flos': 831102046118400.0, 'train_loss': 0.4341429313727185, 'epoch': 7.0})

# Resultados del modelo optimizado contra fichero de Test

In [ ]:
import torch
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [ ]:
# Comprobación de disponibilidad de GPU
if torch.cuda.is_available():
    # Si hay una GPU disponible, la asignamos como dispositivo principal
    device = torch.device("cuda")
    print(f'✅ GPU detectada. Trabajando con: "{torch.cuda.get_device_name(0)}"')
else:
    # Si no hay GPU, el modelo y los tensores irán a la CPU
    device = torch.device("cpu")
    print('⚠️ Trabajando con CPU.')
    print('Para usar la GPU en Colab: Ve al menú superior "Entorno de ejecución" -> "Cambiar tipo de entorno de ejecución" -> Selecciona "GPU T4".')

# Opcional pero recomendado: Ver cuánta memoria VRAM tienes disponible
if device.type == 'cuda':
    memoria_total = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f'Memoria VRAM total disponible: {memoria_total:.2f} GB')

✅ GPU detectada. Trabajando con: "Tesla T4"
Memoria VRAM total disponible: 15.64 GB

## 1. Carga del modelo optimizado desde drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
test_df = pd.read_csv('/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/EXIST2025_test_3_1.csv')

# Limpiamos el índice extra (si existe) y renombramos la columna
if "Unnamed: 0" in test_df.columns:
    test_df = test_df.drop(columns=["Unnamed: 0"])
test_df = test_df.rename(columns={"label_task_3_1_merged": "label"})
test_df["label"] = test_df["label"].astype(int)

campo_texto = 'text'
test_df[campo_texto] = test_df[campo_texto].str.lower()

In [ ]:
model_checkpoint = 'FacebookAI/roberta-base'
model_name = model_checkpoint.split("/")[-1]

model_output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/RoBERTa-base_Optimizado/checkpoint-452'

# Entrenamiento de cada modelo por separado
#model_output_dir = f"{output_dir}/modelo_{model_checkpoint}"

print(f"Cargando tokenizador y mejor modelo desde: {model_output_dir}")
tokenizer_test = AutoTokenizer.from_pretrained(model_output_dir)
model_test = AutoModelForSequenceClassification.from_pretrained(model_output_dir).to(device)
model_test.eval()

Cargando tokenizador y mejor modelo desde: /content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/RoBERTa-base_Optimizado/checkpoint-452

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=2, bias=True)
  )
)

## 2. Predicciones sobre el conjunto de test fijo

In [ ]:
predicciones = []
y_true = test_df['label'].tolist()
y_pred = []

for index, row in tqdm(test_df.iterrows(), total=len(test_df), desc=f"Inferencia en Test ({model_name})"):
    # Usamos la variable campo_texto que definiste antes
    texto = str(row[campo_texto])

    # Tokenización
    inputs = tokenizer_test(texto, return_tensors="pt", padding=True, truncation=True, max_length=128).to(device)

    with torch.no_grad():
        outputs = model_test(**inputs)
        # Softmax para obtener la probabilidad de la clase 1 (Misógino)
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]
        prob_misogino = probs[1].item()

    predicciones.append({
        "id_EXIST": row["id_EXIST"],
        "prob_texto": prob_misogino
    })

    # Decisión binaria (Umbral 0.5)
    y_pred.append(1 if prob_misogino > 0.5 else 0)

Inferencia en Test (roberta-base): 100%|██████████| 502/502 [00:21<00:00, 23.15it/s]

## 3. Resultados oficiales y métricas

In [ ]:
print("\n" + "="*50)
print(f"🏆 RESULTADOS OFICIALES EN TEST FIJO: {model_name}")
print("="*50)
print(f"F1-Score (Macro): {f1_score(y_true, y_pred, average='macro'):.4f}")
print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")
print("\nMatriz de Confusión:\n", confusion_matrix(y_true, y_pred))
print("\nClassification Report:\n", classification_report(y_true, y_pred, target_names=["No Misógino", "Misógino"]))

==================================================
🏆 RESULTADOS OFICIALES EN TEST FIJO: roberta-base
==================================================
F1-Score (Macro): 0.6794
Accuracy: 0.6833

Matriz de Confusión:
 [[199  62]
 [ 97 144]]

Classification Report:
               precision    recall  f1-score   support

 No Misógino       0.67      0.76      0.71       261
    Misógino       0.70      0.60      0.64       241

    accuracy                           0.68       502
   macro avg       0.69      0.68      0.68       502
weighted avg       0.69      0.68      0.68       502

## 4. Guardado del CSV para futuro ensemble

In [ ]:
ruta_guardado = f"/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/RoBERTa-base_Optimizado/predicciones_test_{model_name}.csv"
pd.DataFrame(predicciones).to_csv(ruta_guardado, index=False)
print(f"\n✅ Archivo CSV de predicciones guardado en: {ruta_guardado}")

✅ Archivo CSV de predicciones guardado en: /content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/RoBERTa-base_Optimizado/predicciones_test_roberta-base.csv

# Entrenamiento con el 100% de los datos

## Lectura y etiquetado de Datos

In [ ]:
# ================================
# 1. Carga y preparación de datos
# ================================
import pandas as pd
from sklearn.model_selection import train_test_split
# from datasets import Dataset

print("Cargando el dataset maestro de entrenamiento...")
# Cargamos el TRAIN COMPLETO que contiene el 100% de los datos
df_train = pd.read_csv("/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/EXIST2025_training_3_1.csv")
test_df = pd.read_json('/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/test/EXIST2025_test_clean.json', orient='index')

# Limpiamos el índice extra (si existe) y renombramos la columna
if "Unnamed: 0" in df_train.columns:
    df_train = df_train.drop(columns=["Unnamed: 0"])
df_train = df_train.rename(columns={"label_task_3_1_merged": "label"})
df_train["label"] = df_train["label"].astype(int)

test_df.reset_index(drop=True, inplace=True) # Reseteamos el index del dataframe
test_df = test_df.drop(columns=["id_Tiktok", "video", "url", "annotators", "gender_annotators", "split"]) # Eliminación de columnas que no son relevantes del dataframe

print("Distribución fichero de entrenamiento (Train):")
print(df_train['label'].value_counts())

print("\nNúmero registro fichero de test (competición):")
print(len(test_df))

# train_dataset = Dataset.from_pandas(train_df)
# eval_dataset = Dataset.from_pandas(val_df)

Cargando el dataset maestro de entrenamiento...
Distribución fichero de entrenamiento (Train):
label
0    1306
1    1202
Name: count, dtype: int64

Número registro fichero de test (competición):
674

## Preprocesado del texto

In [ ]:
# Para ver el vocabulario del dataset

import pandas as pd

# Suponiendo que la columna de texto se llama 'text'
# Tokeniza y obtiene todas las palabras
vocabulario = set(
    palabra.lower()
    for fila in df_train["text"].dropna()
    for palabra in fila.split()
)

# Mostrar todo el vocabulario
print(vocabulario)

# (Opcional) Ver el número de palabras únicas
print(f"\nTotal de palabras únicas: {len(vocabulario)}")

{'"dantesamudio11', 'nickname', "guy's", 'educate', 'trait', 'losses', 'overall', 'hacía.', 'hicieron"', 'sostenes?', 'spend', 'unacceptable!', 'lac', 'brake,', 'spin?', 'parecernos', 'mujeres.en', 'vídeo', 'biohazard', 'hace.es', '4\'11",', 'today’s', 'sien,', 'anyone.', 'posta', 'daniels', 'puñalo!', 'ak)ieuid@', 'cabrera,', 'matate.', 'conozco?', 'pisao,', 'editar', 'aaron', 'oídos,', 'kh959', 'aod', 'artista', 'hands', 'vuestro', 'francia,', 'niceness', 'ng', 'arqueño?', 'yesdordccalcomcoldooc', 'muerta', 'legs.', 'baseline.', 'lesbiana', 'pidieron', 'millón,', '4(6', 'instance,', 'upset,', 'listo?', 'miniserie', 'flexibilidad', 'ond', 'socks?', 'mechanics.', 'jiru', "'pibas", 'something,', 'caricias,', 'capítulo?', 'tinta.', 'dryer."', 'tutorials', 'aclaracion', 'grvuzd', 'cesvcv', 'gemido', 'piglet', 'leer', 'frazzled.', 'promedio.', 'amongado', '8;', 'maltrato', 'burrada,', 'model', 'mnldos', 'mrs.', 'feminine,', 'each', 'ofendieron', 'chantajear', 'matan.', 'police,', 'starr,', 'lloran.', 'practicing!', 'aonv', '!1oy', 'amor.es', 'enough', 'hermano.', 'en0s', 'mujer".pero', 'day,', 'du]reply', 'circumference,', 'keys', 'deferencia.', 'never.', 'k', '3.36', 'jonmalexander.', 'xtrakoo', 'pretentious?', 'kamala', 'pies,', 'mitad,', 'fight!', '[dark', 'hopnuf', 'beno)', 'dias', 'graduación', 'establecimientos', 'men', 'limpiado', 'softer,', '{avental', 'convierta', 'jim2on', 'familia,etc.cuando', 'ajedrez.maría,', 'micro-micro-médico.', 'kinds', '30,00', 'deshidratarte.nosotros', '1sb', 'abs', 'oc', 'haríamos', 'sake', 'dependerá', '1co', 'ex-girlfriend,', 'sabes', 'hakleye', 'personas', 'vida!', 'chill.', 'plaid', 'compatible', 'trento.', 'aileen,', 'sahkilvalysse$', 'you', 'man-splaining', 'steel', 'incluyen', 'jamas', 'dijiste', 'valoran', 'vida', "'cause", 'vista', 'doña', 'godhrok', 'language.', 'discuss', 'concentrarte', 'nitrogen', 'agente', 'mymy', 'enter', 'llevan', "'opinante'", 'dick,', 'androgyny.', 'role', 'hombre.a', "{quéu'", 'masculina.piu-piu.jiji.piu!¡arrr!', 'gonu', 'comment,', '74,', 'mío?', 'orlorok26', 'dar?', 'des,', 'dannysexbang21', 'catalinaavilaok', 'correcta', 'amigo', 'par', 'aplicación', 'directamente', 'confinamiento,', 'señoros,', 'crecerá?', 'include', 'sajp', 'ago.', 'chihuhua', 'toilet,', 'pads', 'shit!por', 'vacúnatewa', 'google,', 'actividades', 'anxiety,', '8lbs', 'blunt', 'mostrando', 'compra', 'agridulce', 'copera.', 'intended.', 'asleep.', 'sarcastic', 'genio.este', 'cared', 'partida,', 'ofrezcamos', '60,', 'fo', 'criminal.', 'begin', 'caen.además,', 'acosar', 'black_heart', 'doctoras', 'eches', 'examen.', 'tuyo?', 'ministros.', 'patriarca.', 'opinions?', 'happy.', 'gracioso,', '.', 'jacket,', 'karolg', 'mechanic', 'father.', 'mujeres!', 'bigote', 'manitas,', 'castigar', 'practicamos', 'lone', 'back,', 'suyas?', '[diane)7', 'llore', 'gaphgach_', '17a389', 'infieles.', 'desinfectamos', 'cesta.', 'great-grandma', 'rectus', 'crianza', '1+020', 'tomoya', 'coleras', 'hardships,', 'precioso.', 'johor.', '225r', ')icmmuaacay', '-21=', 'quanimma', 'baby?', 'ofrecida.', 'arpyioprillcpo', 'falsa', 'jazzy,', 'noche?', 'us;', 'ciertos', 'sintiera', 'legally,', 'aylunna', 'hsilovevs,', 'opino', 'awarenessgirl', 'jajaja', 'bendición', 'coqueteo.', 'lanza', 'blanc/couleurs', 'southern', 'mosc', 'hi!', '"vi', 'marilyn', "'usernamebdhdbd", 'vas.', 'país.', 'studies', 'parael', 'qual', 'otro?', 'pecero', 'anerdac', 'actual,', 'parody.', 'jac."', 'sweetie,', 'boluda', 'dinos', 'vasto', 'homofobia,', 'sándwich.', 'diez,', 'sally,', 'app', 'conocen,', 'vendiendo', 'anyway', 'bico', 'unas', 'f2uklel', 'valorarte.', 'arriesga', "'day.", 'mexican', 'rebel,', 'filosofía,', 'casada.', 'saleswoman', 'etiqueta,', 'camera', 'meto', 'mucha', 'dejas,', 'their', 'mujer.y', 'waaahh', 'hagan', 'insects', 'muchas', 'nos', '"morras,', 'zflm', 'peru', 'frú.¡', 'conformaré', '%a', 'profetide', 'habitus,', '00.10,', 'angle', 'af', 'mujencs', 'stepladder?', 'diablo.', 'odio"', 'juan.first', '10.54', 'functional,', 'weekend,', 'idefy', '04', '2p8l', 'meant', 'martin,', '¿has', 'peinare', 'manchado', 'creadora', 'champagne.', 'peces.', 'looe', 'eso,', 'kylie', "n'", 'tastes', 'vencedor,', 'duele,', '"stitch', 'league,', 'saturday?', 'brefran77', 'flick', 'hubo', 'odio,', '-p-8-f-à-2-"-{5', 'ago?', 'human.', 'leaves', 'own.', 'maestra', 'hey!', 'media', 'rojas', 'pomamreporter0', 'chingada,', 'taylor', 'a3aka_o77hkror,', 'deberíamos', 'telemiel', 'lost.', 'tóxica', 'villa.me', 'duele.dejen', '""¡uno,', '~rogers-129a.', 'message', 'fresca', 'mfsna', 'months?', 'desmanejar,', "we'd", '60030', '87,5%', 'repente', 'strangling', '86', 'hurting', 'erckal', 'jenafar,', 'andale.', 'bye', '"wwlainfojoscom', 'complicit', 'papatalo', 'dejárselo', 'mind.', 'chacrin', 'relación?', 'mandato?', 'compañera', 'signs!', 'terror.', 'suelando', 'i@', 'españoles.', 'station,', 'oyendo', 'twice', 'descarta', 'cope', "yourmommaluvsthed's", 'confortable', 'piensenlo', 'channels', 'caln,', '(9a7', '"e.', 'trapped', 'capitalism.', 'opinions.', 'branquias.tuvimos', 'ayudar?', 'noches', 'shout', 'mostrara', '2a2_lay', 'tanto."', 'marriage,', 'realization.', 'w9.', 'convive', 'plot', 'infused', 'kitchens.', 'encontrada', 'pewš', '50k', 'allen,', 'tufo.', 'know."', 'trucos', 'mereces', 'computadora', 'clen', 'read.', 'altura', 'cerotel.', 'sick,', 'anyone..', '_tchalla', '¿sos', 'longer.', 'wendynaffe', 'elope', 'conversar', 'bear', 'bañar.', 'ovaco-verdes', 'jewels.', 'cenar', 'calórico', 'muchísimo', 'shein', '(2)', 'idiots', 'voicemail', 'bien', 'bolsas.', 'šs%lhc),', 'lograrlo,', 'notar', 'meses!', 's86', 'sábados,', 'seguí', 'gustaría...', 'heart!', 'koalitic.', 'responsibilities.', 'predators', 'historia,', '01.06', 'aguantándome', 'nacho', 'abrazos,', 'ground,', 'desfiles', 'bounce,', 'issues.', '12k2c2', 'taught', "everyone's", 'toward', 'tiktokers', 'chamaca', 'llames', 'hooks.este', 'península', 'paccgrioeeeag', 'cencosud', '"tarjeta', 'snow"', 'standpoint', 'it', 'kim', 'cagando', 'lectua.', 'celar,', 'saludameeeé', 'photoshoot', 'tocó,', 'late,', 'man.”', '"esa', 'dibujando', 'novio,', '¿tu', 'acuerdo,', 'cierras', 'sjk?', 'phone,', 'incredible', 'sloficialp€', '¡tá!', 'asaltar!', 'play.you', 'democracia', '1a', 'started', 'nalgas.', 'locura,', 'perreo', 'uplifted', 'white_heart', 'motilado.', 'levels.', 'plumón', 'contactaran', 'unsafe?', 'hígado', 'miembro', 'error.', 'stop.', '2015', 'pretexto,', '2,', 'eran', 'necesario.pero,', 'pair', 'pep', '"¿iba', 'blue', 'machine', 'par.', 'crash,', 'believing', 'guston', 'mixed', 'sale,', 'ith', 'haverz', 'noelia', 'papá",', '"si"', 'adoration', 'ripping!', 'head?he', 'green', 'beautiful?', 'lang', '7l', 'vídeo?', 'r.', 'saldrán', 'femmes,', 'crabajo', 'salpicón', 'o.', 'fusilan', 'memes,', 'hombre".', 'trampos', 'qué', 'pon', 'irrelevantes', 'leales,', 'respetar.por', 'finishing', 'adversos.', 'ln2,', 'rate', 'pibes.caramelo', 'confundamos', 'weight,', 'ganaron', 'upheld.', 'tomín', 'aumento', 'empowered', '"just', 'underserved', 'alejate', '40080uzacreciendo', 'amli0', "s'a2tra", 'jajajajajjajajajajajaj', 'tropezado', 'anchas', 'costado', 'guns,', 'soporto', '"christianosiuuironaldootaku"', 'lie', 'intuición', 'ba-do-ba-do,', 'invisible.', 'sentarse.nunca', 'life-proof),', 'bdsm', '¡uy', 'triste', 'uy', 'vírgenes', 'busy?', 'tutor', 'meses.', 'borrador', 'método', 'pattern', 'centrif', 'tradition', 'lame', 'enclochada', '"purplewashing",', 'acabado', '"ella', 'necesitas,', 'explicar?es', 'exagero', 'health_worker_light_skin_tone', 'aprobacion', 'threat', 'pana,', 'esperando', 'medio', 'presidenta', 'lesbians', 'origen', 'cancellation.', '{', 'coat', 'multifaceted.', 'entrada,', 'street?', 'marcar', 'posa', 'disposable', '2234', 'playboy', 'juiciamiento', 'ayvar,', 'vicaria.', 'camino.', 'agüero!', 'preste?', 'preventivas', 'alude', 'fiesta.', 'kicking', '07yi', 'structure', 'girlfriends', 'happiness.', '¿esposo?oso', 'sought', 'punctuate', 'demás.', '3?', 'sensibles,', 'facile', 'saco"', 'summed', "lookin'", 'miras', 'shawty', 'machista', 'mentira.tienen', 'ipiay', "color's", 'para', '80*59', 'jim2o2', 'masacrar', 'coal', '¿ambos', '2k', 'center', 'violeta', 'same.', 'lano,', '2ll', 'seen', 'segai', 'collection.', 'pebardos', 'llorar,', 'noche...', 'traits', 'salmagundí,', 'equal.', 'jello', 'battery', "you've", 'eructos', 'encuentra?', 'pegó', '982', 'arrives,', 'beta.y', 'yes', 'escuincle!', 'extraño,', 'responderé?', "zoo's", 'huuhu', 'sure?', 'crossed', 'call_me_hand', 'shakin', '#humor', 'questioning', 'jnm', 'pibos,', 'sebastian,', 'guste', 'alguien.número', 'luana.', 'escucharían.', 'ok.allí', 'retos,', 'padreada', 'faced', 'promocionar', '2vaincaoah1ada]as', 'e22%overview', 'sexualized.', 'fachera!', 'looking.', '5fe', 'throws', 'onidringonagnss', 'hi', 'vez,', '#pning', 'to.el', 'jewel.', 'habla,', 'armado.', 'winning,', 'isilove.', 'paocticeo', 'final', 'allá,', 'aprendemos', 'chemistry."', 'desierto', 'censura-denuncia', 'camina', 'mano!', 'quedarnos', 'tiraron', 'belen', 'vuelves', 'collection', 'garganta', 'inválida', 'abuela,', "tommy's", 'moreno,', 'ha,', 'led', 'titty', 'estaremos', 'number;', 'preocupante.', 'dating.', 'oholonrk', 'pinga', '4v', 'atraer', 'accurate', 'running', 'allowed', 'lentes.', 'insect', 'sex.', 'decidiste', 'comentarios', 'zurda', 'chambea!', 'kiss_mark', 'states', 'lives?', 'accidentally', 'innit?', '6yerawev', 'olael', 'forra,', 'know?', '¡suscríbete!', 'rfj', 'tercermundisd', 'bang,', 'struggles.', 'polvos', 'recline', 'ii_kokoro', 'respetó,', 'backs', 'downright', 'miércoles,', 'nacns', '#côá"', 'herramienta', 'linterna,', 'aymanonce', 'espalda', 'lunes,', 'serie.por', 'sanchez', 'a-', 'sorpresa', 'camioneta.', 'dude.', 'redeemed,', 'y', 'cancelled', 'vacation', 'adelantado,', 'pamkaalss.', 'carries', 'thinning?', 'trkhai', 'cruz', 'miami.miami.', 'machito?', 'whatever,', '<*1', 'todos",', 'yo.en', 'pâjâ', 'nonol', 'prom', 'detalles', 'runa', 'tomamos.', 'roommate', 'for?', 'prom?', 'lamont1', 'muer".', 'angels.', 'aceptas', 'nienio_nictil866', "society's", 'gasolina', 'j2rav-un', 'yovi', 'bonito.poniendo...', 'married.', "you'd", 'sod', 'censurados.esto', 'evidence', '39', 'repeticiones', '(nmh', 'tickles', 'atacando."', 'negativity', 'robas', 'pierde', 'francisco?', 'morgan', 'plata?', '#parati', 'años.es', 'emissions', 'ooh.', 'pad.', 'roqucre4', 'divertida.', '"tengo', 'nocturno,', 'budgeting.', 'abordar', 'papa.', '{10)efiri"', 'puerta', 'soqome', 'desmonta', 'tlok', 'diply.com', 'cognitive', 'ot-p-8-f-à-2-"-€', 'casa,', 'readable', 'fat', 'lulú?', 'jealousy.', 'outcomes?', 'suplemento', 'normales', '?oviaikj', 'csm"', 'burbuja', 'sya,', 'ayw', 'chavo', 'smack', 'combina', 'demuestras', 'social?', 'recibiendo', 'report', 'christian', 'not!', '8/10.', 'sanción', 'sororo', 'esperanza.', 'operated', 'intenciones', 'amiguitos,', 'cause', 'desidir', '(pt.5)', 'presidente?', 'maltrate.', 'emñilywking', 'hudi,', 'egocentrismo', 'sit.', 'enojar.', 'salir,', 'contigo.yo', 'paja?', 'faces', 'pollos', 'restricts', 'infierno!', 'surroundings', 'jtate', 'win', '428+2988', 'electricidad', 'centímetros.va', '2i4ris', 'joy,', 'locas', 'años)', '"antonio', 'fábricas', 'gum', 'zany_face', 'reasons.', 'click', 'demanda', 'opaka', '62yeqaw', 'rompo', 'science?', 'acceleration,', 'deals', 'abusador.', 'crabs', 'cabreando', 'cave"', 'gusja.', 'desplazar', 'avergonzarse.para', '"¡cállate!"', 'baja".', 'maletellón,', 'experto,', 'quebramos', 'kinemaster.', 'dibujar.', 'research?', 'men’s_room', 'war?', 'arpyioprilalcpo', 'no.un', '"/', 'damn,', 'esperan.', 'tablet".', 'caga', 'repeticiones,', 'paulinagrandagomezj', 'national', 'nn', 'trashi', 'alter-ego,', 'abandonar', 'lala', 'prbiuegios8', 'gracias!', 'estaré', 'riley?', 'aca', 'not?', '"¡pura', 'liver', '220to.', 'media.', 'ilorando', 'masturbarse?', '¿mínimo', '#everydaysexism', 'worshipping', 'pranks!"', 'véanlo', '@pato_hn32', 'lotion', 'pris', 'witches?', 'straps.', 'cop', 'clientas.', 'macho', '≠', 'daño,', 'dy-4tbl219', 'toast', 'محتاج', 'everyone;', 'reuniones.', "bartholomew69's", 'amenaza.', 'amiga...', 'hospital', 'cream?', 'ap', 'mon', 'prestaba,', 'completo".', 'pewpbww', 'mismas,', 'nutcracker', 'unfair.', 'provocativa', 'casen', '1504', 'guata,', 'neta?', '241', 'tipo,', 'buscando,', 'person_shrugging', 'muévete!', 'voltear', 'manifold', 'tape', '!¡', 'situación,', 'condition.', '"ay,', 'adquirir', 'coli', 'misma.', 'hecho', 'debt', 'stone', 'haibre', 'macaco"', "thackery's", 'tiner.', 'caballeros', 'proyecta,', 'golpea', 'efectiva.', 'familia.la', 'autb', 'todd', 'demonstration', 'carros', 'cuerpo,', 'chismosa', 'shopping,', 'vos', 'ejercicio,', 'mi_mte', 'brasil,', 'mantenerse', 'saltar,', 'negro', 'receta', 'residence,', 'tips.', 'dumber', 'escríbanme', 'bershka', 'trab', 'breed', '¡pum!', 'esterilizarse,', 'south', 'hired', 'kokoro_irene', 'shego', 'bloqueo', 'have', 'head,', '2ver', 'delights', 'amaban,', 'siganmeee', 'divided?', 'ohippi', 'defensor', 'alinaj!', 'hair?', 'relación,', 'dolor', 'primeras', 'estereotipas', 'say', 'florida,', "'ig", 'libertad.¿', 'unappreciated', 'padre.', 'dad?', 'nitro', '0.', 'woman_dancing_light_skin_tone', 'nazca,', 'móvil', 'idealizan?un', 'nephew', 'sexy', 'simpeo', 'covert', 'hoepzz.', 'digital.la', 'francés', 'treasure', 'incomprensible', 'ambulancia', 'lmiay_', 'conocerse,', 'i3j', 'about', 'eoyaliv', 'sjy', 'low.', 'subes', 'cagaste.', 'natun', 'efecto.', "johnbrown5303's", 'linear', '¿recuerdas', '(5nyid', 'eaintj', "campbell's", 'anthony,', 'brain_no_thinky.', 'can’t', 'james', 'acuérdate', 'business,', 'ríes', 'pataditas', 'rj', 'ate', 'invente', 'prayers', 'mee', 'gorca007.', 'mickey', 'rosa",', 'closet', 'vida".', 'variables', 'cooked', 'hijab', 'forecasts,', 'barrer', 'ripper', 'urazagest880', 'roblox', 'monument', 'ioion', 'conoce,', 'numerosas', 'i’ll', 'intento.', 'schnauzer,', 'superzoom', 'amy', 'bulbs', 'tro', 'suoosoui', 'muneres', 'invito', 'edrllsgod', 'demorena', 'empecemos', 'pet', 'espaldas.', 'franko.', 'amargo', 'ex?', 'humo', 'baby_light_skin_tone', 'carro,', "red's", 'soberanía', 'arregló', 'cago', 'distracts', 'veinte', 'viene.', 'moni(u', 'impacte', 'hawk', 'quemaduras', '3rasnaren', 'araña,', 'sentes', '?jake,', 'antes,', 'tktok', 'cònòlos', 'surprisingly', 'blvtox,', 'propiedad!sayuki-senpai,', 'tar', 'key.', 'embristas,', 'tide', 'paso.', 'mind', 'sesenta,', 'respetó', 'tecnica', 'informes,', 'ਦੇ', 'oimzo', 'demons.', 'princess,', 'guarnamar.bajando,', 'hell', 'swarn', 'sevillana', 'almademia_amorconscientetrik', 'qui', 'hubba', 'even.', 'grieve', 'chiquitas', '"he\'s', 'for', 'portrait.', 'smash.', 'pruebas,', 'shopping.', 'businesses', 'about.', 'hac3r', 'gatos,', 'intie', '801is', 'wite', 'habitantes,', 's3x0.', 'hitler', 'sewing', 'htgou', 'manspreading.', 'shot.', 'mis', 'mero', 'air', 'estanca,', 'self-portraits.', 'establecimiento,', 'school.', 'resuene', 'to_', 'ona', 'ataque', 'motherfucker,', 'contradictorias', 'segundo,', 'vinculado,', 'yethquezadas', "pa'", 'snowflake', "'30.", 'trabajó', 'bon', 'shake', 'divertidillo,', 'sistemas', 'prontaldía', '203.', 'it....', 'disgust', 'bonke,', "'k)", 'posibilidades', 'dg!.', 'pregnant_woman_medium-light_skin_tone', 'krbro', '00.12,', 'nue', 'pisado', 'cramping!', 'digital', 'inmigrantes.', 'barclays', 'solemnidad', 'bypass', 'abusadas', '148', '"my', 'stop?', 'reemplazará', '1g', 'compas', 'loudest!', 'thunder', 'eaa?iivima', 'quemado', 'estuviera', 'ghbs@', 'herida,', 'ejercicios', '1417', 'todo,', 'violación.', 'picture', 'accusation,', 'conocer', 'comentario11', 'mic', 'accesibles.', 'sugar', 'metabolic', 'vuela,', 'entiendo', 'desapare', 'racist', 'hill,', 'chick', 'torch', 'gen', 'foto,', 'sufrir', 'god', 'jurado', 'cynthia.', 'eramos', 'cambio,', '"saddle', 'cabecita', 'textures.', 'clodbrok', '7z,', 'feminicidio.', 'mutuamente', 'return.', 'dope', 'onoor', 'quién', '#abogado', 'elsincero', 'solo,', 'perú!', '"cosas', 'unipree?', 'aaa!', 'funarte.', 'conditioned', '"orlarok26', 'todo.', 'dudas.', 'hote', 'america,', 'upon', 'be,', 'contra,', 'flutter.', 'sexista,', 'monitores', ']', 'calientas', 'respondiendo', 'raped', 'work', 'kimberly.', 's00', 'añito', 'ayude', '"papá"', 'soul/dral).', 'julián?', 'windbag.', 'jamdkakdkskdka', 'worry!', 'wechi,', 'menonton!', 'oiegir', 'eternal', 'victimismo', 'lagartona.estoy', 'compromise.', 'goug', 'pbmns', 'suficientes.', 'enojada?', 'atatiana', 'periods', 'gender?', 'unir', 'enseñarle', 'nene', 'derechos.', 'querrás', 'genetically', 'trascendido', '¿así', 'labiales', 'encanta!', 'abusca,', 'cárcel.', 'aristóteles.las', 'incorporarlo', 'interesante".', 'by_hagatoro_12', 'accuse', 'globo', 'retweets.', 'pagas', '~vo)', 'paladuñas.', 'café,', 'nobel', 'urban', 'adrianagallardo338', 'if?', 'skim', 'teoría', 'ejecutivo', 'ring', 'calquicra,', '4*23', 'buque', '{hotpuu', 'slit', 'adds', 'escucho', 'adapui', 'proceso?', 'post.', '¿vistes', 'acaueesls', 're-perdone,', 'criticar', 'prefiere', 'pero', 'tendido', 'cnn', 'arianalasmine,', 'gustan', '952', 'uñas?', 'sarávam,', 'desodorante?', 'mí!', 'promised.', 'hirientes', 'violó.', 'notice', 'ground', 'recommend', 'rest.', '21a', 'fneseaelalj', 'i’d', 'gcamilazambranob', 'measures.', 'planeta', 'awaits.', 'nueva', 'castigo.pues', 'equipo.', 'reflejos', 'amarillistas"', 'humor', 'preocupan', 'actividad', 'park,', 'noviembre,', 'opiniones', '"fancy"', 'got', 'skirts.', 'crotch.', 'cómoda', 'cuerpas', 'pantallas!!!', 'gustando,', 'buts,', 'warning', 'marta', "how's", '124,', 'artem', 'gentle', 'luchó', 'man[', 'jamás,', 'copaka_0t7,', 'gratuita,', 'p2r2ang', 'astronauta,', 'lor.', 'black', 'asistir', 'pnja,', 'attitude,', 'lips.', 'ok_hand_medium-dark_skin_tone', 'hair.', 'autism', 'peleando.', 'adoption', 'pareja.', 'pudo', 'norteamericanas', 'that.', '7nr,', 'bucket.', 'atraen.obviamente', 'vámonos!', 'hoteles', 'hijo.', '2ueato', 'object!', 'tuvieras', 'showers', 'nosoycarolina', 'répondre', 'jugado', 'escuche,', 'consumían', '1o5', '=0', 'close.', 'towels.', 'vístima"', '~se', 'chance', 'chances', 'email', 'propio', 'queen.', 'skid', 'regulinchis.si', 'creanme', 'stepsister', 'estas,', 'cultures', 'vengo', 'extrañaremos', '745,', 'brag', 'investigating', 'neighbor', '0044', 'oil', 'matenía', '"stop."', 'vean', 'basa', 'nerf', 'morlas', 'isptia', 'nuggets.', 'baii', 'magna"', '"carlos', 'venudo', 'mascota', 'prlontom', 'loss?"', 'doubt', 'pedirle', 'están', 'conejo.las', 'dispararon?', 'egreso', 'make-up?"', '€t-si-i', 'veces.', 'unfuck', 'gemuiwe', 'luisa', 'catedral.¡', 'canción', 'hermania!', 'regulados', 'streets', 'desayo,', 'she...', 'puerta,', 'chaves', 'crece,', 'cambiado', 'drama,', 'segura,', 'dinero.es', 'frills,', 'sale', 'toqu', 'masculine.', 'opaka_ot7j,', 'attacked.that’s', 'fácil,', 'child,', 'igualo', "juicy_912's", 'cabrón,', 'mueren', 'gustar.se', 'profesor', 'entender,', '1960s.', 'zapatillas', '5creo', 'mohamed', '"cinco', 'bro?', 'ácido', 'misógino.', 'onda?', 'lección,', 'down."', 'lanzan', 'cual,', '091kyo', 'jim2od', 'vas,', 'flip,', 'tome', 'feeding', 'imaginaste,', 'tenes.', 'secretaría', 'mapnpeot', 'gratuito.', 'adulto.', 'cuantas', 'generamos', 'vuelvo', 'amig@', 'tuyo', 'intended', 'tratando', 'hipocresía.', 'scream!', 'perrea.hoy', 'dandola', 'hermoso', 'heteros', 'profe', 'urazadizámicâ', 'anuncios', 'bofetada.', 'soldier', 'frágil?', 'post', 'desvaloriza', 'vapes.', 'onoe', 'gusta."', 'linda', 'agarrar.', 'ezo', 'decías', 'kara', 'trabajan', 'cruz.', 'venezolanas', 'charli', 'embrismo', 'provide', 'hermana,', 'negative.', 'películacabecera"', 'berraquera', 'estatua', 'clipart.', 'quotes.', 'air.', 'passion.', 'support.', 'break', 'mb', '4oo', 'emily', 'colegio.¿', 'devolución', 'obsessed', '2zs', 'supiste.pues', '#justiceforsarah.', 'tolos', 'conversations', 'ésta', '"amiga",', '-4782', 'afeitar,', 'supremacista', 'agrada', 'lógicamente', 'podemos', 'wcovespomnalihidad', 'included.', 'entro', 'maldito!', 'should!lady', 'summer', 'memory.', 'sink.', 'agarramos', 'fundamental', 'blantons', '128v2', 'grito,', 'fart', 'samuel', 'culo', 'comunicarse,',

In [ ]:
import re

def remove_links(tweet):
    """Takes a string and removes web links from it"""
    tweet = re.sub(r'http\S+', '', tweet)        # remove http links
    tweet = re.sub(r'bit.ly/\S+', '', tweet)     # remove bitly links
    tweet = re.sub(r'\[link\]', '', tweet )      # remove [link]
    tweet = re.sub(r'\[url\]', '', tweet )       # remove [url]
    tweet = re.sub(r'pic.twitter\S+','', tweet)
    return tweet

def remove_users(tweet):
    """Takes a string and removes retweet and @user information"""
    tweet = re.sub('(RT\s@[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)  # remove re-tweet
    tweet = re.sub('(@[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)      # remove tweeted at
    tweet = re.sub(r'\[user\]', '', tweet )                      # remove [user]
    return tweet

def remove_hashtags(tweet):
    """Takes a string and removes any hash tags"""
    tweet = re.sub('(#[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)      # remove hash tags
    return tweet

def remove_av(tweet):
    """Takes a string and removes AUDIO/VIDEO tags or labels"""
    tweet = re.sub('VIDEO:', '', tweet)  # remove 'VIDEO:' from start of tweet
    tweet = re.sub('AUDIO:', '', tweet)  # remove 'AUDIO:' from start of tweet
    return tweet

def remove_emojis(tweet):
    emoj = re.compile("["
        u"\U00002700-\U000027BF"  # Dingbats
        u"\U0001F600-\U0001F64F"  # Emoticons
        u"\U00002600-\U000026FF"  # Miscellaneous Symbols
        u"\U0001F300-\U0001F5FF"  # Miscellaneous Symbols And Pictographs
        u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        u"\U00010000-\U0010FFFF"
        u"\U0001F680-\U0001F6FF"  # Transport and Map Symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642"
        u"\u2600-\u2B55"
        u"\ufe0f"  # dingbats

                      "]+", re.UNICODE)
    return re.sub(emoj, '', tweet)

<>:14: SyntaxWarning: invalid escape sequence '\s'
<>:14: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_3308/1710960392.py:14: SyntaxWarning: invalid escape sequence '\s'
  tweet = re.sub('(RT\s@[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)  # remove re-tweet

In [ ]:
campo_texto = 'text'

df_train[campo_texto] = df_train[campo_texto].str.lower()
test_df[campo_texto] = test_df[campo_texto].str.lower()

## Definición de métricas

In [ ]:
# Función para realizar distintas métricas en ejecución

def compute_metrics(eval_pred):

  ##############
  ## predictions son logits, que son tuplas de la forma [valor1, valor2]
  ## Por ejemplo [-1.5606991,  1.6122842] significa que ha predicho eso para un documento
  ## Eso es lo que pasa a la última capa del transformer (softmax si es binario)
  ## Por eso se utiliza el índice del valor máximo de la tupla, para decir que esa es la clase que predice

  ## label_ids = [0, 1, 1, 0, 1]  # Etiquetas reales
  ## predictions = [
  ##  [0.8, 0.2],  # Predicciones para la primera instancia
  ##  [0.3, 0.7],  # Predicciones para la segunda instancia
  ##  [0.1, 0.9],  # Predicciones para la tercera instancia
  ##  [0.9, 0.1],  # Predicciones para la cuarta instancia
  ##  [0.4, 0.6],  # Predicciones para la quinta instancia
  ##           ]

  ##############

  labels = eval_pred.label_ids
  preds = eval_pred.predictions.argmax(-1)

  # Compute precision, recall, F1-score, and support
  precision, recall, f1, _ = sk.metrics.precision_recall_fscore_support(labels, preds, average="macro")

  # Calculate F1-score for the minority class (label = 1)
  f1_minoritaria= f1_score(labels, preds, pos_label=1)

  # Calculate F1-score for the majority class (label = 0)
  f1_mayoritaria = f1_score(labels, preds, pos_label=0)

  # Calculate accuracy
  acc = sk.metrics.accuracy_score(labels, preds)

  # Calculate Area Under the Curve (AUC)
  AUC = roc_auc_score(labels, preds)

  # Calculate Precision-Recall Area Under the Curve (AUC)
  PREC_REC = average_precision_score(labels, preds)

  return {
      'accuracy': acc,
      'f1': f1,
      'precision': precision,
      'recall': recall,
      'AUC': AUC,
      'f1_minoritaria': f1_minoritaria,
      'f1_mayoritaria': f1_mayoritaria,
      'PREC_REC': PREC_REC
  }

## Entrenamiento del modelo

In [ ]:
# Cargamos el token de HuggingFace que lo tenemos en un fichero oculto e iniciamos sesión

#with open("/home/adrian/Escritorio/DeepSexist/DatasetManagement/EXIST2025DatasetV0.3/huggingfaceToken.txt", "r") as file:
#    hf_token = file.read().strip()

from huggingface_hub import login
from google.colab import userdata

hf_token = userdata.get('HF_TOKEN')

login(token=hf_token)
print("Login completado con éxito")

# ruta_archivo = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/token_hf.txt'

# try:
#     # Abrimos el archivo en modo lectura ('r)
#     with open(ruta_archivo, 'r') as file:
#         hf_token = file.read().strip()

#         # Hacemos el login
#         login(token=hf_token)
#         print("Login completado con éxito")
# except:
#     print("Error: No se ha encontrado el archivo " + ruta_archivo + " en la ruta especificada")

Login completado con éxito

In [ ]:
# Elección del modelo

model_checkpoint = 'FacebookAI/roberta-base'

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [ ]:
# Se carga el modelo preentrenado
n_labels = 2

# El uso de una función de inicialización facilita la repetición del entrenamiento
# Se puede usar la misma función de inicialización en diferentes ejecuciones del código o en configuraciones de entrenamiento diferentes
# Esto facilita la repetición del entrenamiento y la reproducibilidad, ya que se puede inicializar el modelo
# de la misma manera en cada ejecución.

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(model_checkpoint,
                                                              num_labels = n_labels) #, return_dict = True )
                                                              # use_auth_token = 'token propio de HugginFace')

In [ ]:
# Para saber el nombre del modelo
model_name = model_checkpoint.split("/")[-1]
model_name

'roberta-base'

In [ ]:
# Selección de hiperparámetros
#BATCH_SIZE = 32
BATCH_SIZE = 16
NUM_TRAIN_EPOCHS = 3
#LEARNING_RATE = 3e-5
LEARNING_RATE = 1e-5
MAX_LENGTH = 128
WEIGHT_DECAY = 0.1

In [ ]:
def tokenize_data(examples):
  return tokenizer(examples[campo_texto], truncation=True, max_length=MAX_LENGTH, padding=True)

In [ ]:
from transformers import Trainer, TrainingArguments

optim = ["adamw_hf", "adamw_torch", "adamw_apex_fused", "adafactor", "adamw_torch_xla"]

training_args = TrainingArguments(
    output_dir = 'results',
    num_train_epochs = NUM_TRAIN_EPOCHS,
    learning_rate = LEARNING_RATE,
    per_device_train_batch_size = BATCH_SIZE,
    per_device_eval_batch_size = BATCH_SIZE,
    load_best_model_at_end = True,
    metric_for_best_model = 'f1', # Cambiar la metrica por la que queremos ajustar
    weight_decay = WEIGHT_DECAY,
    save_strategy = 'no',
    save_total_limit = 3,
    optim = optim[1],
    push_to_hub = False,
    greater_is_better = True,
    logging_strategy = 'epoch'
)

#output_dir = '/home/adrian/Escritorio/DeepSexist/TrainingBooks/Task3.1/Research/ModelosTransformers'
output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/SubidasCompeticion/' + model_name

# Entrenamiento de cada modelo por separado
model_output_dir = f"{output_dir}/modelo_{model_checkpoint}"

# Convierte directamente los DataFrames de Pandas a Datasets de Hugging Face
train_dataset = Dataset.from_pandas(df_train)

# Reseteamos el formato para que no haya fallos
train_dataset.reset_format()

# Obtenemos los nombres de todas las columnas originales
columns_train = train_dataset.column_names

#Protegemos la columna "label" para no eliminarla accidentalmente

columna_etiqueta = "label" if "label" in columns_train else "labels"

if columna_etiqueta in columns_train:
    columns_train.remove(columna_etiqueta)

encoded_train_dataset = train_dataset.map(tokenize_data, batched=True, remove_columns=columns_train)

# Redefinimos model_init aquí para aplicar la congelación (Layer Freezing)
# def model_init():
#     # 1. Cargamos el modelo base
#     model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)
#     # 2. Congelamos todas las capas base (el "cerebro")
#     for param in model.base_model.parameters():
#         param.requires_grad = False
#     # El classifier sigue estando activo por defecto
#     return model

# Descongelación parcial de las últimas 3 capas

# def model_init():
#     # 1. Cargamos el modelo base
#     model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)

#     # 2. Congelamos TODO el cerebro base por defecto
#     for param in model.base_model.parameters():
#         param.requires_grad = False

#     # 3. Buscamos dónde guarda el modelo sus capas (esto varía según el modelo que estemos trabajando)
#     if hasattr(model.base_model, 'encoder') and hasattr(model.base_model.encoder, 'layer'):
#         capas_transformers = model.base_model.encoder.layer
#     elif hasattr(model.base_model, 'layers'):
#         capas_transformers = model.base_model.layers
#     else:
#         print("No se encontró la estructura de capas estándar. Se entrenará solo con la cabeza.")
#         capas_transformers=[]

#     # 4. Descongelamos solo las últimas 3 capas para que se adapten al vocabulario (TikTok)
#     capas_a_descongelar = 3
#     if len(capas_transformers) >= capas_a_descongelar:
#         print("Descongelando las últimas " + str(capas_a_descongelar) + " capas de un total de " + str(len(capas_transformers)))
#         for capa in capas_transformers[-capas_a_descongelar:]:
#             for param in capa.parameters():
#                 param.requires_grad = True
#     return model

# Inicializa el entrenador
trainer = Trainer(
    model_init = model_init,
    args=training_args,
    compute_metrics = compute_metrics,
    train_dataset=encoded_train_dataset,
    processing_class=tokenizer,
)

# Entrena el modelo
trainer.train()

# Guarda el modelo entrenado
trainer.save_model(model_output_dir)

Map:   0%|          | 0/2508 [00:00<?, ? examples/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  499MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## Generación del fichero de predicciones

Generación del fichero de predicciones con el formato de subida a la plataforma.

### 1. Rutas y configuración

In [ ]:
# Ruta al modelo definitivo que entrenaste con el 100% de los datos
RUTA_MODELO_FINAL = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/SubidasCompeticion/roberta-base/modelo_FacebookAI/roberta-base"

# Ruta al Test Oficial Limpio (el que no tiene etiquetas)
RUTA_TEST_JSON = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/test/EXIST2025_test_clean.json"
# Nota: Si estás en Colab, asegúrate de subir este archivo a tu Drive y cambiar la ruta, ej:
# RUTA_TEST_JSON = "/content/drive/MyDrive/.../EXIST2025_test_clean.json"

# Ruta donde quieres guardar el JSON final para subir a la web
RUTA_SUBMISSION_JSON = "/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/SubidasCompeticion/roberta_test_oficial.json"

### 2. Carga del test oficial

In [ ]:
print("Cargando el test oficial limpio...")
try:
    df_test = pd.read_json(RUTA_TEST_JSON, orient="index")
except Exception as e:
    print(f"Error al leer el JSON. Intentando sin orient='index': {e}")
    df_test = pd.read_json(RUTA_TEST_JSON) # A veces el formato no requiere orient="index"

# Si 'orient="index"' te dejó los IDs como índice, reseteamos para tenerlos como columna
if 'id_EXIST' not in df_test.columns and 'id' in df_test.columns:
     df_test = df_test.rename(columns={'id': 'id_EXIST'})
elif 'id_EXIST' not in df_test.columns:
     df_test['id_EXIST'] = df_test.index

df_test.reset_index(drop=True, inplace=True)

Cargando el test oficial limpio...

In [ ]:
# Limpiar columnas innecesarias (las que venían en tu script original)
columnas_a_eliminar = [
    "id_Tiktok", "video", "url", "annotators", "gender_annotators",
    "split", "lang", "path_video", "number_annotators"
]
# Eliminamos solo las que realmente existan en el df para evitar errores
columnas_existentes = [col for col in columnas_a_eliminar if col in df_test.columns]
df_test = df_test.drop(columns=columnas_existentes)

print(f"Total de vídeos en el test oficial: {len(df_test)}")

Total de vídeos en el test oficial: 674

### 3. Preparación del modelo (tokenización)

In [ ]:
print(f"Cargando Tokenizador y Modelo desde {RUTA_MODELO_FINAL}...")
tokenizer = AutoTokenizer.from_pretrained(RUTA_MODELO_FINAL)
model = AutoModelForSequenceClassification.from_pretrained(RUTA_MODELO_FINAL)

Cargando Tokenizador y Modelo desde /content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/SubidasCompeticion/roberta-base/modelo_FacebookAI/roberta-base...

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
def preprocess_function(examples):
    # Asegúrate de que la columna de tu JSON que contiene el texto se llama 'text'
    # Si se llama 'tweet' o de otra forma, cámbialo aquí:
    texto_col = 'text' if 'text' in examples else list(examples.keys())[0] # Fallback burdo
    return tokenizer(examples['text'], padding="max_length", truncation=True, max_length=128)

In [ ]:
test_dataset = Dataset.from_pandas(df_test)
# Guardamos los IDs originales antes de mapear, por si acaso
ids_test = test_dataset['id_EXIST']

print("Tokenizando datos de test...")
test_dataset = test_dataset.map(preprocess_function, batched=True)

Tokenizando datos de test...

Map:   0%|          | 0/674 [00:00<?, ? examples/s]

### 4. Predicción con trainer

In [ ]:
print("Realizando predicciones...")
# Creamos un Trainer vacío solo para predecir
trainer = Trainer(model=model)

# La función predict devuelve un objeto PredictionOutput.
# Las predicciones reales están en .predictions (los logits)
predictions_output = trainer.predict(test_dataset)

# Aplicamos argmax para pasar de logits a la clase (0 o 1)
predicted_labels = predictions_output.predictions.argmax(axis=-1)

# Asignamos las predicciones al dataframe original
df_test["predicted_label"] = predicted_labels

Realizando predicciones...

In [ ]:
df_test['predicted_label'].value_counts()

predicted_label
0    396
1    278
Name: count, dtype: int64

### 5. Formateo al estándar PyEvall

In [ ]:
import json

print("Generando archivo de sumisión en formato PyEvALL...")

output_json = []
for index, row in df_test.iterrows():
    # El test_case oficial suele ser "EXIST2025" o "task1". Usa el que te hayan indicado.
    entry = {
        "test_case": "EXIST2025",
        "id": str(row["id_EXIST"]),
        # Convertimos 1 a "YES" y 0 a "NO"
        "value": "YES" if int(row["predicted_label"]) == 1 else "NO"
    }
    output_json.append(entry)

# Asegurar que la carpeta de destino existe
os.makedirs(os.path.dirname(RUTA_SUBMISSION_JSON), exist_ok=True)

# Guardar
with open(RUTA_SUBMISSION_JSON, "w", encoding="utf-8") as f:
    json.dump(output_json, f, indent=2)

print(f"✅ ¡Completado! Archivo guardado en: {RUTA_SUBMISSION_JSON}")

# Pequeño chequeo de balance
print("\nBalance de predicciones enviadas:")
df_check = pd.DataFrame(output_json)
print(df_check['value'].value_counts())

Generando archivo de sumisión en formato PyEvALL...
✅ ¡Completado! Archivo guardado en: /content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/SubidasCompeticion/roberta_test_oficial.json

Balance de predicciones enviadas:
value
NO     396
YES    278
Name: count, dtype: int64