In [ ]:
!pip install -q pytorch-lightning datasets transformers evaluate accelerate scikit-learn

In [ ]:
# Instalacion de librerias
import random
import torch
import numpy as np
import os
from pytorch_lightning import seed_everything
import matplotlib.pyplot as plt
import seaborn as sns
import re

seed_val = 42
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)# Store the average loss after eachepoch so we can plot them.
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
os.environ["TF_DETERMINISTIC_OPS"] = "1" # See:https://github.com/NVIDIA/tensorflow-determinism#confirmed-current-gpu-specific-sources-of-non-determinism-with-solutions
seed_everything(42, workers=True)

from datasets import Dataset, DatasetDict #, load_metric EN PRINCIPIO ESTÁ DESCONTINUADO, TENDREMOS QUE BUSCAR OTRA ALTERNATIVA
import pandas as pd
import sklearn as sk
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score, f1_score
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, \
TrainingArguments, Trainer, pipeline, EarlyStoppingCallback
from huggingface_hub import login

INFO:lightning_fabric.utilities.seed:Seed set to 42

In [ ]:
# Comprobación de disponibilidad de GPU
if torch.cuda.is_available():
    # Si hay una GPU disponible, la asignamos como dispositivo principal
    device = torch.device("cuda")
    print(f'✅ GPU detectada. Trabajando con: "{torch.cuda.get_device_name(0)}"')
else:
    # Si no hay GPU, el modelo y los tensores irán a la CPU
    device = torch.device("cpu")
    print('⚠️ Trabajando con CPU.')
    print('Para usar la GPU en Colab: Ve al menú superior "Entorno de ejecución" -> "Cambiar tipo de entorno de ejecución" -> Selecciona "GPU T4".')

# Opcional pero recomendado: Ver cuánta memoria VRAM tienes disponible
if device.type == 'cuda':
    memoria_total = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f'Memoria VRAM total disponible: {memoria_total:.2f} GB')

✅ GPU detectada. Trabajando con: "Tesla T4"
Memoria VRAM total disponible: 15.64 GB

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Lectura y etiquetado de Datos

In [ ]:
# ================================
# 1. Carga y preparación de datos
# ================================
import pandas as pd
from sklearn.model_selection import train_test_split
# from datasets import Dataset

print("Cargando el dataset maestro de entrenamiento...")
# Cargamos el TRAIN_MASTER que contiene el 80% de los datos (el test fijo ya está guardado aparte)
df_train_master = pd.read_csv("/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/EXIST2025_training_3_1_master.csv")
test_df = pd.read_csv('/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/EXIST2025_test_3_1.csv')

# Limpiamos el índice extra (si existe) y renombramos la columna
if "Unnamed: 0" in df_train_master.columns:
    df_train_master = df_train_master.drop(columns=["Unnamed: 0"])
df_train_master = df_train_master.rename(columns={"label_task_3_1_merged": "label"})
df_train_master["label"] = df_train_master["label"].astype(int)

if "Unnamed: 0" in test_df.columns:
    test_df = test_df.drop(columns=["Unnamed: 0"])
test_df = test_df.rename(columns={"label_task_3_1_merged": "label"})
test_df["label"] = test_df["label"].astype(int)

# División dinámica: 90% Train, 10% Validation (extraído solo del bloque maestro)
# Mantenemos random_state para que la validación sea estable entre pruebas del mismo modelo
train_df, val_df = train_test_split(df_train_master, test_size=0.10, stratify=df_train_master["label"], random_state=42)

print("Distribución fichero de entrenamiento (Train):")
print(train_df['label'].value_counts())

print("\nDistribución fichero de validación (Valid):")
print(val_df['label'].value_counts())

print("\nDistribución fichero de test (estático):")
print(test_df['label'].value_counts())

# train_dataset = Dataset.from_pandas(train_df)
# eval_dataset = Dataset.from_pandas(val_df)

Cargando el dataset maestro de entrenamiento...
Distribución fichero de entrenamiento (Train):
label
0    940
1    865
Name: count, dtype: int64

Distribución fichero de validación (Valid):
label
0    105
1     96
Name: count, dtype: int64

Distribución fichero de test (estático):
label
0    261
1    241
Name: count, dtype: int64

# Preprocesado del texto

In [ ]:
# Para ver el vocabulario del dataset

import pandas as pd

# Suponiendo que la columna de texto se llama 'text'
# Tokeniza y obtiene todas las palabras
vocabulario = set(
    palabra.lower()
    for fila in df_train_master["text"].dropna()
    for palabra in fila.split()
)

# Mostrar todo el vocabulario
print(vocabulario)

# (Opcional) Ver el número de palabras únicas
print(f"\nTotal de palabras únicas: {len(vocabulario)}")

{'ass.', 'vuelto', 'fachito', 'ridiculizando', 'altarpiece', 'lgbtqia+', '7k8k', 'españoles.', 'qusd', 'pibeg,', 'pa', 'sd', 'inocencia.', 'exes.', 'violence', 'screams', 'callace', 'duck.', 'doctor’s', 'un', 'débiles,', 'prácticas', '{1a62*812i', 'sexualmente', 'rociota.', 'thick', 'what!', 'doubt', 'traigo', 'guno', 'machistas', 'gustó".', 'association', 'divorcio,', 'feminista', 'básicas', 'posición.', 'agredir', '330', 'sacaron', 'cis.', 'uy,', 'hac3r', 'qisa?invtn', 'tirada', 'eba', 'ritmo', 'baaol', 'robados?', 'boom!', 'pibardas".', 'temer?', 'stayed', 'principal.', 'pregunta', 'acto', 'detenidas', 'usted,', '13,', 'ਦੀ', 'insertando', 'capitán.', 'suicidas.', 'ignorant', 'coincide', 'horribles,', 'vez,', '"libre', '<192', 'calistenico', 'medallita,', 'denle', 'descanso', 'mismo."', 'tratará', 'importa?', 'village.', 'week,', 'apología', 'escandaloso', 'ponytail,', 'president,', 'burrow.', 'men”', 'duda.', 'posesión', 'portrait', 'おまかおまかおまかおまかおまかおまかおまか', 'sydney', 'independiente', 'uniprees.', 'cuanto', 'nada!', 'testosterone-based', 'sentarte,', 'picturing', 'bájate', 'rollercoaster.', 'inform', 'reflejo', 'receipts', 'yep.', 'similar,', 'gym', 'sedes', 'funcionaria', 'aoasau', 'dentales.', 'scary,', 'jake,', 'harassed.', 'bitty', 'enamorarme.', 'estética,', 'lidiaste', '#fyp.', 'lgtbq', 'pair', 'fansexva', 'incomodidad.', 'aspen.', 'incitieran', 'ver.según', 'ur', 'credibility', 'invented', 'cargador', 'huevas', 'left', 'historia', 'witch.', 'rude', 'pesadilla', 'huevo', 'cuadrado.creeper', 'mundial.en', '4regato', 'panas.¿quien', 'todos",', 'kike.delcid', 'starving', 'jotaro!', 'temario', 'insurance!', 'pagarte', 'tiran', 'necesitaremos.', 'limpio.', 'offset', 'sentada', 'brecha', 'pidieron', 'esconderse', 'alive', 'gangsters?', 'got', 'favoritas', 'tarefe', 'viverón', "society's", 'pude', 'led', 'dedicado', 'recuperar', '2-51-|', 'empty,', '13-year-old', 'perrita', 'verga', 'discutes', 'facts,', '"jazz', '1/20', 'business,', '2044', 'perfectly', 'encontré', 'galletas,', 'serious?', 'motiloo', 'yeah?', 'ciscoloaava.', 'singer,', 'exhilarating', "partner's", 'piojos', 'gustan', 'unidos', 'drummer', 'lloras,', 'recibiendo', 'qffice', 'face_with_raised_eyebrow', '$8,000', 'opción,', 'coco,', 'neighbor', 'usually', 'please.', 'starr,', 'extorsionan', 'y,', 'second-degree', '"a"', 'cavvinki', 'idea,', 'direcig', 'él.', 'consta', 'versatilidad', '2a2_lay', 'pobre', 'valor.', 'íntimo', 'articles', 'hang?', 'víctima.ojalá', 'ezaudiaz', 'llevan', 'llamo', 'maraton', 'egreso', 'results', 'hombres', 'elmomento', 'noar', 'accuse', 'sostengo', 'icontacto', 'discuten', 'bass."', 'cope', 'márquez', 'pers0nal', "isn't", 'decisión"', 'mon-binary.', 'turtle,', 'suppose', "rollin'", 'fav.', 'jo', 'lie,', 'ulies', 'somethin', 'della', 'foot', 'ezeidesaw', 'escuche,', 'commitment', 'xo', 'times".el', 'resuene', 'gollum', 'carbeeson', '890k,', 'medí', 'oppressors', 'resilience', 'seamos', 'brrrr,', 'emirate.', '2i1j0', 'aah', 'llegara', 'equivocarme', 'seoul.', 'spirit.', 'entendido.', 'gratuito', 'resulting', 'tant0', 'etuan', 'rk,', 'básquetbol.', 'broma,', 'imwdym', "brother's", 'schnauzer,', 'café".elido', 'zw', 'desposeído,', 'pierde.', 'feo.sus', '#fl.', 'grab,', 'analizar', 'progressive', 'eldiario.es', 'observando', 'guard', 'cogidos', 'invites', 'cola', '25', 'pregunta.', 'esperando"', 'surf', "'27'", '18o', "'d0ls.", 'karanr', 'torn', 'babiesel', 'audio/video', 'popularity', "jcan't", 'rio', 'disco_', 'delas', '8', 'constitución.la', 'anterior', 'pills', 'syempre', 'distancia.', 'inocentes', 'serio?', 'comprensible,', 'interesa', 'pocunchcaaeunaum', 'jazzmaster', '00.07', 'infuriating.', 'nuevito.', 'folio', 'routine.', 'instrumentalización', 'mexicans', 'solid.', 'círculos', 'masculina?', 'joined', 'lichi', 'f-j1', 'roma', 'condicionan,', 'yct529', 'fotógeno', 'spare', 'falso.', 'involves', 'sola.saludos.', 'objectifying', 'salta', 'wanted.', 'anyways.', 'zip', 'denoting', 'option,', 'obra', 'smr', 'refuse', 'dudbre', 'inclusivo?', 'carencias', 'sano.', 'table', 'response.', 'mujer.', 'resto.', 'pablo', 'recalcitrante', 'collar', 'sanos', 'española', 'todos."', 'microphone', 'scoop', 'scorpio,', 'not!', 'atenembaum.', 'género",', 'valid,', 'pitan', 'lies.', '24,', 'salmón', 'adopted', 'yurneih', 'jonysanz24', 'faulty', 'cocodrilo.', 'seguidores,', 'ittt.', '"wake', 'facheras,', 'bella', 'preview', 'announced', 'holiday.', 'bonitos?', 'immaturity.', 'regamos', 'vacono', 'superficial,', '¿legal?', '<100lbs', 'puedo!', 'cuestión.', 'pío,', 'váyase.', '"u', 'gustav.', 'anthem,', '"comigo",', 'they', 'snapchat,', 'truco', 'sesenta', 'enlo', 'frescos', 'y...', 'bicicleta?', 'purpose.', 'comunismo.', 'genericos', 'enlasis.', '24n', 'attractive,', 'consecuencia', 'stacey,', 'frágil,', '*aviso', 'handsome', 'race!"', 'seralbañalledana', 'andó', 'está.', 'koaa', 'auxiliar', 'vamos!', 'tontería.otra', 'contigo?', 'unicornio', 'perdona', 'opposite.', "phone's", 'grecia', 'halal', 'beggars.', 'cocoroko', 'candidato', 'averokoria', 'reparto', 'crew,', '178398hixi', '4ir5ro8u', 'salud', 'obos', 'observed', 'pro-vida.', 'vegetariana.', '4ô', 'jamás,', 'hables', 'pérdidas,', 'lactancia', 'preso.', 'problem,', 'ayude.viva', 'amenazó', 'bin', 'sick.', 'capcut,', 'confiar', 'existence?', 'crocodile', 'tecnica', '"an', 'murder', 'acknowledge', '7377c', 'demons', 'límite', 'best', 'imposibles.', 'looe', '#waka', 'mama', 'robbery', 'subjects', 'utilizándolo', 'reveal…redneckstyle', 'masterclass,', 'enojada.', 'chingados!', 'estás', '2€', '"gets', 'no.', 'lamento,', 'denúnciarlo', 'gouga', '44', 'dodos', 'uñas', 'alimentan', 'pregnancy,', '1964', 'weeks,', 'racismo.francisco.', 'rompes', 'will.', 'grandma', 'soin.', 'igualdad.', 'preocupes!', 'personas?ok', '¿será', 'map', 'protocolo', 'lloran', 'mom?', 'garbage', 'reporta', 'genética', 'pluma.', 'none', 'marchas,', '3.36', 'pregunto', 'likely', 'matenía', 'tensar', 'sálimo', 'reason,', 'backhand_index_pointing_up_medium-light_skin_tone', 'regresale', 'tak', 'paying.', 'judicial.', 'razones.la', 'piedritas', '3,', 'mom', 'mujer"', '¿acaso', 'thing?', 'instituto!', 'correr,', 'extraordinary', 'olvides.', '11/14/2020,', 'heveay', 'himalaya.', 'single,', 'one-dimensional', 'secrets.', 'celebrarlo', 'prettiest?', 'app', 'saldrán', 'arroz', 'humano.', 'ayala', 'midsize', 'b', 'new.', 'opiniones', 'cibsandibusd', 'relaciones', '@?ockster20', 'respuesta!', 'slide', 'cirujano', '"él', 'gou]reply', 'empieza', 'relación', 'tilkt8k', 'beneath', 'homicide.', 'late-stage', 'juegan', 'quien', 'mero', 'compliments', 'centang', 'down!', 'intenta', "'turbo_deinielagu", 'armado.', 'comointurones?', 'stallion', 'grande,', 'renunciar', "'nlidhb", '"hara-sasa-irabibi-tabibibi-wapita-wim-wapen-nan-woha-hah-tata-tatu-tuku-teyaku"', 'inghsto', 'pronouns?', 'religión.', 'ethic', 'daniel', 'rapto.', 'drain', 'ntenogaek', 'abusiva,', 'ensayo', 'queremos.', 'ogee,', 'willowthesquirrel', 'anunció', '98', "zoo's", 'artist', 'cuánto', 'esperaba', 'aquí."', 'lasano.', 'insult.', 'refieren?', 'coqueta,', 'nipple.', 'countryside', 'colaboradores.', 'escuché;', 'garis', 'aaas', 'completo', 'i...', 'canta', 'obós', 'habilidades."', 'stallion.', 'mexicano,', 'adivinen', 'fantasía', 'desarticulación', 'respondiendo', 'anossu)c', 'front.', 'cari,', 'boy.', 'syrup.', 'pijamada', 'jodan,', 'viste,', 'contraseña', 'fila".', 'sentimentalismo.', 'tiraron', 'puntos', "verne'?", 'ridículas.', 'day.', 'programa.', 'chose', 'hace.es', '<1a8eefisi5', 'vendrán', 'anygome', 'alcanzar', 'tenerle.', 'indicada', 'armas,', 'insulto?', 'acusan', '"la', 'pivas¡', 'domésticas', 'atacados', '"¡vieja', 'marcó', 'seductress.', 'inconveniente,', 'visiting', 'específica,', 'reframe', 'stranger,', 'inyid', 'shi', 'acéptenlo', 'pepper', 'numero', "wonderin'", 'vestidito!', 'cramps', 'ceden', 'agotada,', 'llorará,', 'inseparables', 'agresores', '1478', 'recientemente,', '2225', '88l', 'mae,', 'exactly', 'fra', 'walking', 'sí.el', 'monopoly!', 'choose', 'earthquake.', 'psychic', 'ayudan', 'tiña', 'feminism?', 'fact.', 'muge', 'compa!', 'cuotas.', 'dollars.', '40', 'buen', 'titled', '||', 'sentimos', 'senq1', '1205', '0906.', 'chess', 'criminals', 'earring?', 'quemando', 'unhygienic', 'afeitar,', 'x7i>', 'dobson?', 'biologically', 'técnicas', 'queens', 'ahí.en', 'menonton!', 'sexual', 'whack', 'aguirre', 'rlsaris', 'huyes.', 'minute,', 'dijeron', 'conceptualize', 'relate?', 'abiertos', 'responderle', 'anticipado', '9ax', 'descanso.', 'brother?', 'subía', 'definition', 'frutas', '623', 'clarify', 'growing_heart', 'zh', 'jhdolin', 'major', 'wireless', 'tenets', '(alupt', 'callar.cuando', 'libro', 'cherished.', 'mommygracel.', 'enamorada.', 'vivieran', 'arianalasmine,', 'lady,', 'garlic.', 'dispararon.', '4442', 'vargas', 'doyt8m', 'let’s', 'apoyó', 'guy', 'repente.', 'brothers_twinzj.', 'never', 'normalizamos', 'leeds.', 'piesa', 'preocupe!', 'gb', 'sueltan', 'vivas', 'pibardas', '{19/0', 'dp', 'literal.', 'escucharás', 'tendrán', '2a', 'enojados.', 'p0', 'días', 'apariencia,', 'avergonzar.', 'peruanas.', 'mezcla.', 'defecto.', 'esperas', 'you.boats', 'conozco', "40'),", '"tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-tit-así', 'terminado', '"o"', 'pítale', 'bubbles,', 'taxi', "@'", 'activated*', 'chips', 'raaea', 'attention...', 'nuevas', 'acta', 'hypermasculinized.', 'haz', 'like?', 'generación', 'apps,', 'wrong,', 'tranquila', 'levantar', '"whitefem"', '#notallwomen', 'maye', '"cute",', 'triangular', "'rosa", 'georgie.', 'disconnect', 'code.', 'stepsister', 'pérdida', 'valiosa', 'pero,', 'hablo.', 'vivas.los', 'jjja', 'ara', 'term?', '.futbol1splei', 'matan,', 'grados', "j'", 'convocado', 'saracisnerosg', 'abandon', 'young', 'cállense', 'acoso.', 'murcia', 'último,', 'subirse', 'pobres.', 'gobernante', 'violentos', 'mírala,', 'pilas', 'varón,', 'ambición,', 'bg3y', 'yeah.', 'gorgeous,', 'enojado?', 'dynamic', 'revise,', 'fatality!', 'pasión', 'due', 'machito', 'excuses', 'discourse', 'based', 'ooa', 'opción', 'secundaria,', 'sexistas.', 'growth.', 'being', 'aldair?', 'seeker"', 'colored', 'craving', 'pensaban', 'logic"', 'ademorena', 'teme', 'rompió', 'hit', 'brandon,', 'baby!', 'pivas.¡', 'físico,', 'sucedió,', 'mosquoando,', 'aquellos', 'luquitas', 'ear', 'versátil', 'divertido', 'problems', 'humiliation', 'anticiparnos', 'muneres', 'duelen', 'muchísimos', 'cold,', 'departamentos.', 'tienda', 'mayores...', 'lb', 'asistir.el', 'caitlinnrowe', 'largo?', 'austria', 'l),', 'doscientos', '°sex', '|scand', 'muito', 'bacer', 'esperar!', 'smacks', 'working.', 'cockr),', "you're", 'promise!', 'isidoro', 'tech', 'ahorrar', 'die.', 'marvin', 'momento', 'cinco.', 'коя', 'first,', 'temblando.', 'presentado', 'michurri.ganó', 'quinto', 'mandarina', 'soltería.', 'cursando', 'empezamos', 'grito?', 'azuay!', 'favorite', 'harris,', '3cm?', 'pov', 'cintura', 'colors', 'dream', 'prove', 'era?', 'trabajado', 'abrazó', 'schmuck', 'imoquamayt', 'u/', 'compartiré', 'hey,', 'vigilantes', 'impulsado', 'become', '𝐭𝐚𝐛𝐮́!', 'lion', 'caritas.', 'entrada', 'rally', '(nyi', 'parody.', 'bottle_with_popping_cork', 'anhelos.', 'cartugales.el', 'graffiti', 'violación', 'youme?', 'almazones,', 'farisu', 'expresara', 'raquel', '2gec', 'contigo!', 'up.', 'llorar,', 'okay?', 'hacerlo.antes', '🆁🅸🅽🅶🆄🅴́', 'conversation,', 'understand', 'portabilidad', 'piryuk', 'argument?', 'deny', 'presume,', 'gal', 'ángeles.', 'uflol', 'alinaj!', 'porque?', 'platillo', 'à2f', 'pabiola.', 'logic?', 'guardia', 'wrist', 'make-up?"', 'already.', 'wild', 'flag', 'loco', 'power.', 'gerrysays.', 'snitch', 'alvarez', 'toxic774isr', 'chavo,', "'tist)<", 'refacheros.', 'crow?', 'ido', 'rasgos', 'shame', "2'yawctaoco", 'rowland', 'reproducirse.quien', 'menstruación.', 'cielo,', 'giving', 'corrupción.', 'oxígeno', 'vi', 'naruto', 'mission,', 'marcho.', 'bajitos', 'quién', 'utilizaste', 'beat,', 'equipajes.', 'curvas', 'from.', 'mis...¿', 'grave,', 'hicieron', 'admit,', 'spice.', 'destrozos,', 'necesitas,', '"débil",', 'bye.', 'disco', 'av', 'trozo', 'varios', 'aspin', 'andrés,', 'departamento', 'crizd', 'virulencia,', 'negativity', 'homeboy.', '{nj', 'hombres?', 'raging', 'bad?', 'novios.', 'dicto', 'activated', 'facebook', 'kg,', 'mejoras', 'saltando', 'sea...', 'interview,', 'brain', 'información.', 'rentas.', 'afganos', 'feel.', 'harmed.', 'inequality', 'succeed.', 'kanye', 'varía', 'envidioso', 'possible', 'chiapas', 'bala,', 'avisara', 'burlar', 'mjeres', '"¡ah,', 'ac.', 'parejas,', 'malandra!', "stepbrother's", '4-3', 'fazer,', 'koda', 'uber', 'naciones', 'opiniones,', 'cumplen.', 'papa!', 'aodengraph', 'deberían', 'achieving', 'tf', 'garza', 'businesses', 'finjo', '01.07', 'feminiza', 'gusta', 'hoy.somos', 'będę', 'santi', 'other,', 'nonhormonal', 'seres', 'característica', 'olvidas', 'guys.', 'max,', 'alcanza', 'tradition', '2021?', 'pictures', 'identifying', 'seguido', 'suso/2', 'flequillo.', '"invisibiliza"', 'nacer', 'sandy', 'balón', 'jpg', 'pals', 'ytinum?', 'rentas', 'b?', 'profesionales.', 'dinastías', 'continue', 'exploding_head', 'salcebã', 'style.pówie', 'lasso.', 'buscó"', 'oye.', '#gmj8', 'profetide', 'self', 'tarde.', 'doctor.gracias.y', 'esperes', 'liking', 'denmark', 'vancouver', 'graduaron', ']', 'corner.', 'hm999', 'conociendo', 'common?', 'she...', 'level', 'basar', 'táctica.', 'encarga', 'amistades', 'fatu', 'psycho', 'o7', 'frenes,', 'serpiente', 'mao', 'extraordinarias', 'siadico', 'termo', 'secundarios', 'pretender', 'estudio,', 'complex', 'femenina.', 'planchaba,', 'rick', 'tráiganle', 'pregunta,', 'bounce', 'iii', 'demográfico,', 'sexistas,', 'mistake.', 'no.un', 'orfanato,', 'pendejo', 'malvada', 'woman_medium-light_skin_tone', 'interests?', 'allowed?"', 'generally', "'mthe", 'comisaría.', 'condescendiente', 'indispensable', 'saco', "1n(4,th6'", 'hurts!', 'marico?', 'elliptical', 'lip', 'bat', "'xx,", 'e', 'cometió.', 'usa,', 'jdy16,/', 'hernández', 'pretexto', 'enrique', 'semester', 'pélame.', 'contladroaa.', 'rubbish', 'tolerancia', 'lobo,', 'captivated', 'tula', 'aquí', 'fut.', 'fair', 'vibrantes', 'varias', 'canon.', 'depict', 'lujo', 'itji', 'mía,', 'cluvo', 'ofemde', 'ponemos', 'tras', '13]', 'ball.', 'hombro,', 'aquí.', 'jonmalexander.', 'caño', 'rociomontesdeocaefice', 'huerta.', "men's.", 'fantasma,', 'survivors', 'ratas!', 'hurn', 'sruthi_thampi_.', '#comedy', 'respetotareas', 'estáis', 'actualidad.', 'quieran', 'seguí', 'tercermunosz', 'qualifications', '"machirulos".', 'horse_face', 's16', 'pública', 'twitter.', 'organizadas', 'vivo.', 'lidera', 'deep', '{urf', "there're", 'references', 'fart.', 'hearing', 'vsilo', 'enojadas', 'acostumbrados', 'monke', 'pasó,', 'laughed', 'analicemos,', 'him.', 'umio', 'giantess', '04,', 'severe', 'try"', 'genitales.', '"¡uh!', 'jaden,', 'encerrados,', 'ignoraste,', 'much,', '¿adivinen', 'submundo', 'ornrs', 'gaslight', 'contrapointoint', 'gea', 'away.', 'dreams.', 'slightly', 'most.', 'varón.', 'somebody', 'impetus.', 'territorio', 'algebra', 'badness', '"he\'s', 'mek', 'alternativas', 'marilyn', 'dudéis', 'remove', 'guatemala.se', 'cochinita.', 'tus', 'insulting', 'qu', 'esperma', 'dieta,', 'include', 'comparte', 'nubla', 'lte', 'debating', 'ninksyb', ')', 'tuov', 'tijuana,', 'descargar.', 'checo,', 'tomatoes,', 'limpieza,', 'volvimos', 'decía', 'broke,', 'fuerte', 'chores)', 'offer', 'leonardomartincas', 'período', 'panel', '{acentalcovespomnalilidad', 'salvó', 'imi', 'hacen".', 'hayalao', 'arte,', 'hangout.', 'muleres', 'incumbe!', 'moment?', 'aunq', 'j"', 'genders', 'biphobic', 'enviar', 'sálvame,', 'privilege', 'güey!', 'superior,', '7=,', 'ha,', 'mcion', 'presunta', 'bonnetusa', '"si', 'entendiste?', 'pedophile', 'stroke,', 'frikis', 'detenga', 'gospel', 'chico.', 'adulta,', 'invisibilizados', 'experimentar', 'onion,', 'part,', 'genocida', 'bailar,', 'davids,', 'pb', 'hipócrita...', 'pr@', 'melryoo]', 'os', 'dive', 'cutie', 'afecta,', 'delightful.', 'eo', 'terrorista?como', 'there?', 'ooh!', 'pequeños', 'institucional', '.ftbl219iaki', 'shortcut', 'auto-percibe', 'crow.', 'moral,', 'correa.', 'exageradx",', 'around.', '"feminidadidad', 'erckal', 'cristo,', 'recuerden', 'valientes,', 'pitching', 'sstudiq', 'barcos.', 'vhe', '"drama".dos,', 'faltar,', 'meses.', 'percepción', 'neurons', 'reyes,', 'an,', 'oaah30', 'socialista', 'c.', 'pasado?', 'hemingway.', 'depilé.', 'forget,', 'nothing,', 'information."', 'minutos', 'suicida', 'christ', '0-', 'rap', 'mexico', 'sucedió', 'resultados', 'vas', 'discriminando,', '0b', 'gajorobe', 'persona,', 'parte,', '[author', 'propia,', 'ainda', 'grupo,', 'forever,', 'gritos', 'extravagante', '17.05', 'hamburguesa,', 'fisuras.', 'kind', 'metiendo', 'exageran,', 'efafcf', 'long', 'mina,', 'expecting', 'aquel', "'m", 'siguió', 'adoption', 'vacúnatyven', 'again!', 'conozco.', 'bolsita,', 'podrida', 'unido', 'molesta,', 'ellos', '3r6', 'urazagest/8n', 'are?', "musk's", 'lucía', 'again."', 'acudir,', 'cuestiona', 'hog', 'gustavof12', 'offer.', '"feministas"', 'ofende', 'justozzybeingozzy', 'aaarmstrong', 'seductor!!', 'fiestas', 'thankful', 'exposición,', '3536', 'mari,', 'inicios', 'especial.', 'apply', 'secondly,', 'defendes', 'víctima.', 'pleasing', 'seguir?', 'dormido', 'ropas', 'cintura,', 'knickknacks,', 'alumnos,', 'others.', 'casarse', 'h0uo', 'understanding', 'pana,', 'derecho', 'diario.', 'garciaa6', 'congruente', 'reyes', 'katymvlg8.', '130', 'revisamos', 'identifican', 'loca...', 'ford', 'ashley', 'alcohólico.', 'matters', 'sí.', 'pebardos', 'station.', 'carefok', 'específicamente', 'internacionales', 'información,', 'discussion.', 'vidrio', 'work.', 'eighty-five.', 'mujeres!!', 'يكون', 'evelyn.', 'nata', 'mienten,', 'recibir', 'depends', 'mete', "nothing's", '(1', 'cuatro,', 'llorando,', 'tide"', 'públicos.según', 'tenga,', '¿quieres', '“not', 'ancló', 'domingo', 'video.', 'jjeverettrose.', 'saludan', 'semafora.', 'quiebre,', '(rar)', 'simply', 'dik-dik', 'necesitamos', 'tall.', 'hom', 'training.', 'outfits.', 'aob', 'coro', 'supérate', 'uñapa.¡', 'miranda', 'pressure', 'equipo!', "ain't", 'down,', 'jos', 'loob', 'papis', 'homc', 'felicita', 'psychology.', 'aparece.', 'twins,', 'relatad', 'iv', 'hi', '#foryoupage', 'romántico".', 'callado.', 'zorro', 'tenéis', 'oficial,', 'bomollaagbd', 'modales."', "judge's", 'calf,', 'education°', 'vistas', 'interesaba,', 'hombre.diario', 'haters', 'attacked', 'explicarle', 'estados', 'caigan', 'economía.argentina', 'amenazando,', 'sírenesí,', 'yes!yes!the', 'repeticiones,', 'llegar', 'men"', 'lasociedadgiro', 'traitor,', '¿', 'dedicatoria.', 'eboj', 'lash,', '(esta', "'rn", 'parents', 'dammit_that', 'andrés', 'woman?!', '=,', 'audio', 'kiss_mark', 'tóxica', 'wage', 'mejpres', 'normalmente', 'do2u', 'mind.', 'favor.es', 'dulces', 'mundo.ya', 'conformar', 'cuidado.', 'eres', 'funar.', 'todes', 'at', 'tiempo."', 'vegana.', 'tezumás,', 'pudimos', 'tendaspgr', 'dismissive', 'futvhe', 'play.', 'almond', 'suddenly', 'onyki,', 'abandonarte', 'mulu-9,', 'many,', 'asustan', 'twiningeface', 'contesta!"".y', 'sara', '42s,', 'sirva', 'ilorando', '1-', 'winners', 'basta,', 'bone,', 'vomita', 'anderson,', 'criticar', 'uo', '220to.', 'sirve', 'sesgos', 'locura', 'wi-fi', 'acuerdo.', 'rampas.', 'efectiva.los', 'boomers', 'shbsa', "pris@'", 'canpl,', 'cambiarlo', 'thumbs_down', 'orejona,', 'courage', 'vete', 'together?', "scientist's", 'elegant', 'fulano', '155', 'course.', 'credibilidad.', 'clawca,', 'stars', 'vo5,', 'people,', 'cerró', 'masó', 'rich', 'machistas,', 'bitches.', '

In [ ]:
import re

def remove_links(tweet):
    """Takes a string and removes web links from it"""
    tweet = re.sub(r'http\S+', '', tweet)        # remove http links
    tweet = re.sub(r'bit.ly/\S+', '', tweet)     # remove bitly links
    tweet = re.sub(r'\[link\]', '', tweet )      # remove [link]
    tweet = re.sub(r'\[url\]', '', tweet )       # remove [url]
    tweet = re.sub(r'pic.twitter\S+','', tweet)
    return tweet

def remove_users(tweet):
    """Takes a string and removes retweet and @user information"""
    tweet = re.sub('(RT\s@[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)  # remove re-tweet
    tweet = re.sub('(@[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)      # remove tweeted at
    tweet = re.sub(r'\[user\]', '', tweet )                      # remove [user]
    return tweet

def remove_hashtags(tweet):
    """Takes a string and removes any hash tags"""
    tweet = re.sub('(#[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)      # remove hash tags
    return tweet

def remove_av(tweet):
    """Takes a string and removes AUDIO/VIDEO tags or labels"""
    tweet = re.sub('VIDEO:', '', tweet)  # remove 'VIDEO:' from start of tweet
    tweet = re.sub('AUDIO:', '', tweet)  # remove 'AUDIO:' from start of tweet
    return tweet

def remove_emojis(tweet):
    emoj = re.compile("["
        u"\U00002700-\U000027BF"  # Dingbats
        u"\U0001F600-\U0001F64F"  # Emoticons
        u"\U00002600-\U000026FF"  # Miscellaneous Symbols
        u"\U0001F300-\U0001F5FF"  # Miscellaneous Symbols And Pictographs
        u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        u"\U00010000-\U0010FFFF"
        u"\U0001F680-\U0001F6FF"  # Transport and Map Symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642"
        u"\u2600-\u2B55"
        u"\ufe0f"  # dingbats

                      "]+", re.UNICODE)
    return re.sub(emoj, '', tweet)

<>:14: SyntaxWarning: invalid escape sequence '\s'
<>:14: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_622/1710960392.py:14: SyntaxWarning: invalid escape sequence '\s'
  tweet = re.sub('(RT\s@[A-Za-z]+[A-Za-z0-9-_]+)', '', tweet)  # remove re-tweet

Convertimos todo a minúsculas

In [ ]:
campo_texto = 'text'

train_df[campo_texto] = train_df[campo_texto].str.lower()
val_df[campo_texto] = val_df[campo_texto].str.lower()
test_df[campo_texto] = test_df[campo_texto].str.lower()

# Definición de métricas

In [ ]:
# Función para realizar distintas métricas en ejecución

def compute_metrics(eval_pred):

  ##############
  ## predictions son logits, que son tuplas de la forma [valor1, valor2]
  ## Por ejemplo [-1.5606991,  1.6122842] significa que ha predicho eso para un documento
  ## Eso es lo que pasa a la última capa del transformer (softmax si es binario)
  ## Por eso se utiliza el índice del valor máximo de la tupla, para decir que esa es la clase que predice

  ## label_ids = [0, 1, 1, 0, 1]  # Etiquetas reales
  ## predictions = [
  ##  [0.8, 0.2],  # Predicciones para la primera instancia
  ##  [0.3, 0.7],  # Predicciones para la segunda instancia
  ##  [0.1, 0.9],  # Predicciones para la tercera instancia
  ##  [0.9, 0.1],  # Predicciones para la cuarta instancia
  ##  [0.4, 0.6],  # Predicciones para la quinta instancia
  ##           ]

  ##############

  labels = eval_pred.label_ids
  preds = eval_pred.predictions.argmax(-1)

  # Compute precision, recall, F1-score, and support
  precision, recall, f1, _ = sk.metrics.precision_recall_fscore_support(labels, preds, average="macro")

  # Calculate F1-score for the minority class (label = 1)
  f1_minoritaria= f1_score(labels, preds, pos_label=1)

  # Calculate F1-score for the majority class (label = 0)
  f1_mayoritaria = f1_score(labels, preds, pos_label=0)

  # Calculate accuracy
  acc = sk.metrics.accuracy_score(labels, preds)

  # Calculate Area Under the Curve (AUC)
  AUC = roc_auc_score(labels, preds)

  # Calculate Precision-Recall Area Under the Curve (AUC)
  PREC_REC = average_precision_score(labels, preds)

  return {
      'accuracy': acc,
      'f1': f1,
      'precision': precision,
      'recall': recall,
      'AUC': AUC,
      'f1_minoritaria': f1_minoritaria,
      'f1_mayoritaria': f1_mayoritaria,
      'PREC_REC': PREC_REC
  }

# Entrenamiento del modelo

In [ ]:
# Cargamos el token de HuggingFace que lo tenemos en un fichero oculto e iniciamos sesión

#with open("/home/adrian/Escritorio/DeepSexist/DatasetManagement/EXIST2025DatasetV0.3/huggingfaceToken.txt", "r") as file:
#    hf_token = file.read().strip()

from huggingface_hub import login
from google.colab import userdata

hf_token = userdata.get('HF_TOKEN')

login(token=hf_token)
print("Login completado con éxito")

# ruta_archivo = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/token_hf.txt'

# try:
#     # Abrimos el archivo en modo lectura ('r)
#     with open(ruta_archivo, 'r') as file:
#         hf_token = file.read().strip()

#         # Hacemos el login
#         login(token=hf_token)
#         print("Login completado con éxito")
# except:
#     print("Error: No se ha encontrado el archivo " + ruta_archivo + " en la ruta especificada")

Login completado con éxito

In [ ]:
# Elección del modelo

model_checkpoint = 'pysentimiento/robertuito-base-uncased'

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

config.json:   0%|          | 0.00/677 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/323 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/858k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

In [ ]:
# Se carga el modelo preentrenado
n_labels = 2

# El uso de una función de inicialización facilita la repetición del entrenamiento
# Se puede usar la misma función de inicialización en diferentes ejecuciones del código o en configuraciones de entrenamiento diferentes
# Esto facilita la repetición del entrenamiento y la reproducibilidad, ya que se puede inicializar el modelo
# de la misma manera en cada ejecución.

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(model_checkpoint,
                                                              num_labels = n_labels) #, return_dict = True )
                                                              # use_auth_token = 'token propio de HugginFace')

In [ ]:
# Para saber el nombre del modelo
model_name = model_checkpoint.split("/")[-1]
model_name

'robertuito-base-uncased'

# Fine-tuning

In [ ]:
# Selección de hiperparámetros
#BATCH_SIZE = 32
BATCH_SIZE = 16
NUM_TRAIN_EPOCHS = 15
#LEARNING_RATE = 3e-5
LEARNING_RATE = 1e-5
MAX_LENGTH = 128
WEIGHT_DECAY = 0.1

In [ ]:
def tokenize_data(examples):
  return tokenizer(examples[campo_texto], truncation=True, max_length=MAX_LENGTH, padding=True)

In [ ]:
from transformers import Trainer, TrainingArguments

optim = ["adamw_hf", "adamw_torch", "adamw_apex_fused", "adafactor", "adamw_torch_xla"]

training_args = TrainingArguments(
    output_dir = 'results',
    num_train_epochs = NUM_TRAIN_EPOCHS,
    learning_rate = LEARNING_RATE,
    per_device_train_batch_size = BATCH_SIZE,
    per_device_eval_batch_size = BATCH_SIZE,
    load_best_model_at_end = True,
    metric_for_best_model = 'f1', # Cambiar la metrica por la que queremos ajustar
    weight_decay = WEIGHT_DECAY,
    eval_strategy = 'epoch',
    save_strategy = 'epoch',
    save_total_limit = 3,
    optim = optim[1],
    push_to_hub = False,
    greater_is_better = True,
    logging_strategy = 'epoch'
)

#output_dir = '/home/adrian/Escritorio/DeepSexist/TrainingBooks/Task3.1/Research/ModelosTransformers'
output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/' + model_name

# Entrenamiento de cada modelo por separado
model_output_dir = f"{output_dir}/modelo_{model_checkpoint}"

# Convierte directamente los DataFrames de Pandas a Datasets de Hugging Face
train_dataset = Dataset.from_pandas(train_df)
valid_dataset = Dataset.from_pandas(val_df)

# Reseteamos el formato para que no haya fallos
train_dataset.reset_format()
valid_dataset.reset_format()

# Obtenemos los nombres de todas las columnas originales
columns_train = train_dataset.column_names
columns_valid = valid_dataset.column_names

#Protegemos la columna "label" para no eliminarla accidentalmente

columna_etiqueta = "label" if "label" in columns_train else "labels"

if columna_etiqueta in columns_train:
    columns_train.remove(columna_etiqueta)
if columna_etiqueta in columns_valid:
    columns_valid.remove(columna_etiqueta)

encoded_train_dataset = train_dataset.map(tokenize_data, batched=True, remove_columns=columns_train)
encoded_valid_dataset = valid_dataset.map(tokenize_data, batched=True, remove_columns=columns_valid)

# Redefinimos model_init aquí para aplicar la congelación (Layer Freezing)
# def model_init():
#     # 1. Cargamos el modelo base
#     model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)
#     # 2. Congelamos todas las capas base (el "cerebro")
#     for param in model.base_model.parameters():
#         param.requires_grad = False
#     # El classifier sigue estando activo por defecto
#     return model

# Descongelación parcial de las últimas 3 capas

# def model_init():
#     # 1. Cargamos el modelo base
#     model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)

#     # 2. Congelamos TODO el cerebro base por defecto
#     for param in model.base_model.parameters():
#         param.requires_grad = False

#     # 3. Buscamos dónde guarda el modelo sus capas (esto varía según el modelo que estemos trabajando)
#     if hasattr(model.base_model, 'encoder') and hasattr(model.base_model.encoder, 'layer'):
#         capas_transformers = model.base_model.encoder.layer
#     elif hasattr(model.base_model, 'layers'):
#         capas_transformers = model.base_model.layers
#     else:
#         print("No se encontró la estructura de capas estándar. Se entrenará solo con la cabeza.")
#         capas_transformers=[]

#     # 4. Descongelamos solo las últimas 3 capas para que se adapten al vocabulario (TikTok)
#     capas_a_descongelar = 3
#     if len(capas_transformers) >= capas_a_descongelar:
#         print("Descongelando las últimas " + str(capas_a_descongelar) + " capas de un total de " + str(len(capas_transformers)))
#         for capa in capas_transformers[-capas_a_descongelar:]:
#             for param in capa.parameters():
#                 param.requires_grad = True
#     return model

# Inicializa el entrenador
trainer = Trainer(
    model_init = model_init,
    args=training_args,
    compute_metrics = compute_metrics,
    train_dataset=encoded_train_dataset,
    eval_dataset=encoded_valid_dataset,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
    processing_class=tokenizer,
)

# Entrena el modelo
#trainer.train()

# Guarda el modelo entrenado
#trainer.save_model(model_output_dir)

Map:   0%|          | 0/1805 [00:00<?, ? examples/s]

Map:   0%|          | 0/201 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/435M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

# Optimización de hiperparámetros

Esto lo hacemos porque ha sido el modelo transformers de entre multilingüe, español e inglés que mejor nos ha funcionado.

In [ ]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.5)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.2)

In [ ]:
import optuna
from transformers import Trainer, TrainingArguments, AutoModelForSequenceClassification, EarlyStoppingCallback

model_checkpoint = 'pysentimiento/robertuito-base-uncased'
n_labels = 2

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)

In [ ]:
def optuna_hp_space(trial):
    return {
        # Busca un Learning Rate entre 1e-5 y 5e-5 (escala logarítmica)
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True),

        # Penalización para no memorizar (entre 0.01 y 0.1)
        "weight_decay": trial.suggest_float("weight_decay", 0.01, 0.1),

        # Calentamiento del motor (entre el 0% y el 10% de los datos)
        "warmup_ratio": trial.suggest_float("warmup_ratio", 0.0, 0.1),

        # Tamaño de batch (que elija el que mejor generalice)
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [8, 16])
    }

In [ ]:
training_args = TrainingArguments(
    output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/Optuna/robertuito-base-uncased',
    num_train_epochs = 5,           # Lo capamos a 5 épocas por intento para que la búsqueda sea rápida
    eval_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True,
    metric_for_best_model = 'f1',   # Apuntamos a tu métrica
    greater_is_better = True,
    fp16 = True,                    # Compresión activada para que Colab vuele
    push_to_hub = False,
    logging_strategy = 'epoch',
    disable_tqdm = False            # Para ver la barrita de progreso
)

In [ ]:
trainer = Trainer(
    model_init = model_init,
    args = training_args,
    compute_metrics = compute_metrics,
    train_dataset = encoded_train_dataset,
    eval_dataset = encoded_valid_dataset,
    processing_class = tokenizer,
    # Tolerancia cero: si en 2 épocas no mejora, aborta el intento y pasa al siguiente
    callbacks = [EarlyStoppingCallback(early_stopping_patience=2)]
)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
print("🔍 Iniciando rastreo bayesiano de hiperparámetros con Optuna...")

best_trial = trainer.hyperparameter_search(
    direction = "maximize",                    # Queremos el número más alto posible
    backend = "optuna",                        # Motor de búsqueda
    hp_space = optuna_hp_space,                # Nuestra función de límites
    n_trials = 10,                             # Va a hacer 10 intentos (aprox 1.5 - 2 horas)
    pruner=optuna.pruners.MedianPruner(n_startup_trials=2, n_warmup_steps=1),
    compute_objective = lambda metrics: metrics["eval_f1"] # El objetivo es maximizar tu eval_f1
)

[I 2026-07-13 18:08:37,543] A new study created in memory with name: no-name-903ddb83-0bb0-469b-8a95-37491cf43f98

🔍 Iniciando rastreo bayesiano de hiperparámetros con Optuna...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 18:11:01,191] Trial 0 finished with value: 0.7076143659711076 and parameters: {'learning_rate': 1.3531582322766579e-05, 'weight_decay': 0.028064012455117263, 'warmup_ratio': 0.05156408596857102, 'per_device_train_batch_size': 8}. Best is trial 0 with value: 0.7076143659711076.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 18:12:51,936] Trial 1 finished with value: 0.6945821397434301 and parameters: {'learning_rate': 3.984176512859095e-05, 'weight_decay': 0.018805272557703097, 'warmup_ratio': 0.07982232084118894, 'per_device_train_batch_size': 8}. Best is trial 0 with value: 0.7076143659711076.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 18:15:09,276] Trial 2 finished with value: 0.7123163841807909 and parameters: {'learning_rate': 1.7000170492301625e-05, 'weight_decay': 0.08924206913748048, 'warmup_ratio': 0.09931949758223213, 'per_device_train_batch_size': 16}. Best is trial 2 with value: 0.7123163841807909.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 18:18:14,483] Trial 3 finished with value: 0.7054176913331842 and parameters: {'learning_rate': 2.631460069973236e-05, 'weight_decay': 0.060965838512568524, 'warmup_ratio': 0.0834002138938443, 'per_device_train_batch_size': 8}. Best is trial 2 with value: 0.7123163841807909.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 18:20:21,695] Trial 4 finished with value: 0.7082582582582583 and parameters: {'learning_rate': 2.3578793064736142e-05, 'weight_decay': 0.02327199189671455, 'warmup_ratio': 0.0012229049719949205, 'per_device_train_batch_size': 8}. Best is trial 2 with value: 0.7123163841807909.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 18:21:57,114] Trial 5 finished with value: 0.706140350877193 and parameters: {'learning_rate': 2.638544527100523e-05, 'weight_decay': 0.04198841419217928, 'warmup_ratio': 0.03930948600357074, 'per_device_train_batch_size': 8}. Best is trial 2 with value: 0.7123163841807909.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-07-13 18:22:18,888] Trial 6 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 18:22:58,119] Trial 7 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-07-13 18:23:12,941] Trial 8 pruned.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-07-13 18:23:31,401] Trial 9 pruned.

In [ ]:
print("\n" + "="*50)
print("🚀 ¡BÚSQUEDA TERMINADA! 🚀")
print(f"🏆 El mejor F1 conseguido ha sido: {best_trial.objective}")
print(f"⚙️ Los hiperparámetros ganadores son:")
for key, value in best_trial.hyperparameters.items():
    print(f"   - {key}: {value}")
print("="*50)

==================================================
🚀 ¡BÚSQUEDA TERMINADA! 🚀
🏆 El mejor F1 conseguido ha sido: 0.7123163841807909
⚙️ Los hiperparámetros ganadores son:
   - learning_rate: 1.7000170492301625e-05
   - weight_decay: 0.08924206913748048
   - warmup_ratio: 0.09931949758223213
   - per_device_train_batch_size: 16
==================================================

# Entrenamiento del modelo después de la optimización de hiperparámetros

In [ ]:
from transformers import Trainer, TrainingArguments, AutoModelForSequenceClassification, EarlyStoppingCallback
from datasets import Dataset

In [ ]:
# 1. Configuración del modelo
model_checkpoint = 'pysentimiento/robertuito-base-uncased'
n_labels = 2

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=n_labels)

In [ ]:
# 2. Las Constantes Ganadoras de la Optimización con Optuna
BATCH_SIZE = 16
NUM_TRAIN_EPOCHS = 10       # Le damos margen completo para buscar su verdadero pico
LEARNING_RATE = 1.7000170492301625e-05  # La tasa de aprendizaje perfecta descubierta
WEIGHT_DECAY = 0.08924206913748048      # Regularización fuerte anti-overfitting
WARMUP_RATIO = 0.09931949758223213      # Calentamiento lineal de gradientes

optim = ["adamw_hf", "adamw_torch", "adamw_apex_fused", "adafactor", "adamw_torch_xla"]

In [ ]:
# 3. Rutas automáticas a tu Google Drive Principal
output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/RoBERTuito_Optimizado'
model_output_dir = f"{output_dir}/modelo_final_tfm"

training_args = TrainingArguments(
    output_dir = output_dir,
    num_train_epochs = NUM_TRAIN_EPOCHS,
    learning_rate = LEARNING_RATE,
    per_device_train_batch_size = BATCH_SIZE,
    per_device_eval_batch_size = BATCH_SIZE,
    load_best_model_at_end = True,
    metric_for_best_model = 'f1',
    weight_decay = WEIGHT_DECAY,
    warmup_ratio = WARMUP_RATIO,     # <-- Inyectamos el Warmup ratio ganador
    eval_strategy = 'epoch',
    save_strategy = 'epoch',
    save_total_limit = 2,
    optim = optim[1],                # adamw_torch estable
    fp16 = True,                     # Compresión en GPU activa para máxima velocidad
    push_to_hub = False,
    greater_is_better = True,
    logging_strategy = 'epoch'
)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

In [ ]:
# 4. Preparación de Datasets (Conversión limpia de tus DataFrames de Pandas)
train_dataset = Dataset.from_pandas(train_df)
valid_dataset = Dataset.from_pandas(val_df)

train_dataset.reset_format()
valid_dataset.reset_format()

columns_train = train_dataset.column_names
columns_valid = valid_dataset.column_names

columna_etiqueta = "label" if "label" in columns_train else "labels"

if columna_etiqueta in columns_train:
    columns_train.remove(columna_etiqueta)
if columna_etiqueta in columns_valid:
    columns_valid.remove(columna_etiqueta)

encoded_train_dataset = train_dataset.map(tokenize_data, batched=True, remove_columns=columns_train)
encoded_valid_dataset = valid_dataset.map(tokenize_data, batched=True, remove_columns=columns_valid)

Map:   0%|          | 0/1805 [00:00<?, ? examples/s]

Map:   0%|          | 0/201 [00:00<?, ? examples/s]

In [ ]:
# 5. Inicialización del Entrenador de Producción
trainer = Trainer(
    model_init = model_init,
    args = training_args,
    compute_metrics = compute_metrics,
    train_dataset = encoded_train_dataset,
    eval_dataset = encoded_valid_dataset,
    callbacks = [EarlyStoppingCallback(early_stopping_patience=3)], # Margen de 3 épocas sin mejorar para parar
    processing_class = tokenizer,
)

print("Lanzando el entrenamiento definitivo de XLM-RoBERTa con los mejores hiperparámetros...")
trainer.train()

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Lanzando el entrenamiento definitivo de XLM-RoBERTa con los mejores hiperparámetros...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: pysentimiento/robertuito-base-uncased
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=678, training_loss=0.3800700885356352, metrics={'train_runtime': 165.3011, 'train_samples_per_second': 109.195, 'train_steps_per_second': 6.836, 'total_flos': 712373182387200.0, 'train_loss': 0.3800700885356352, 'epoch': 6.0})

In [ ]:
# 6. Guardado de seguridad eterno en tu Google Drive
print("Asegurando los pesos óptimos del modelo en la nube...")
trainer.save_model(model_output_dir)
print("¡Operación completada! El mejor modelo está a salvo en mi Drive.")

Asegurando los pesos óptimos del modelo en la nube...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

¡Operación completada! El mejor modelo está a salvo en mi Drive.

# Resultados contra fichero de Test

In [1]:
import torch
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [2]:
# Comprobación de disponibilidad de GPU
if torch.cuda.is_available():
    # Si hay una GPU disponible, la asignamos como dispositivo principal
    device = torch.device("cuda")
    print(f'✅ GPU detectada. Trabajando con: "{torch.cuda.get_device_name(0)}"')
else:
    # Si no hay GPU, el modelo y los tensores irán a la CPU
    device = torch.device("cpu")
    print('⚠️ Trabajando con CPU.')
    print('Para usar la GPU en Colab: Ve al menú superior "Entorno de ejecución" -> "Cambiar tipo de entorno de ejecución" -> Selecciona "GPU T4".')

# Opcional pero recomendado: Ver cuánta memoria VRAM tienes disponible
if device.type == 'cuda':
    memoria_total = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f'Memoria VRAM total disponible: {memoria_total:.2f} GB')

⚠️ Trabajando con CPU.
Para usar la GPU en Colab: Ve al menú superior "Entorno de ejecución" -> "Cambiar tipo de entorno de ejecución" -> Selecciona "GPU T4".

## 1. Carga del mejor modelo desde drive

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
test_df = pd.read_csv('/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/EXIST2025_test_3_1.csv')

# Limpiamos el índice extra (si existe) y renombramos la columna
if "Unnamed: 0" in test_df.columns:
    test_df = test_df.drop(columns=["Unnamed: 0"])
test_df = test_df.rename(columns={"label_task_3_1_merged": "label"})
test_df["label"] = test_df["label"].astype(int)

campo_texto = 'text'
test_df[campo_texto] = test_df[campo_texto].str.lower()

In [5]:
model_checkpoint = 'pysentimiento/robertuito-base-uncased'
model_name = model_checkpoint.split("/")[-1]

output_dir = '/content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/' + model_name

# Entrenamiento de cada modelo por separado
model_output_dir = f"{output_dir}/modelo_{model_checkpoint}"

print(f"Cargando tokenizador y mejor modelo desde: {model_output_dir}")
tokenizer_test = AutoTokenizer.from_pretrained(model_output_dir)
model_test = AutoModelForSequenceClassification.from_pretrained(model_output_dir).to(device)
model_test.eval()

Cargando tokenizador y mejor modelo desde: /content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/robertuito-base-uncased/modelo_pysentimiento/robertuito-base-uncased

Loading weights:   0%|          | 0/201 [00:01<?, ?it/s]

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(30000, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(130, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=2, bias=True)
  )
)

## 2. Predicciones sobre el conjunto de test fijo

In [6]:
predicciones = []
y_true = test_df['label'].tolist()
y_pred = []

for index, row in tqdm(test_df.iterrows(), total=len(test_df), desc=f"Inferencia en Test ({model_name})"):
    # Usamos la variable campo_texto que definiste antes
    texto = str(row[campo_texto])

    # Tokenización
    inputs = tokenizer_test(texto, return_tensors="pt", padding=True, truncation=True, max_length=128).to(device)

    with torch.no_grad():
        outputs = model_test(**inputs)
        # Softmax para obtener la probabilidad de la clase 1 (Misógino)
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]
        prob_misogino = probs[1].item()

    predicciones.append({
        "id_EXIST": row["id_EXIST"],
        "prob_texto": prob_misogino
    })

    # Decisión binaria (Umbral 0.5)
    y_pred.append(1 if prob_misogino > 0.5 else 0)

Inferencia en Test (robertuito-base-uncased): 100%|██████████| 502/502 [03:49<00:00,  2.19it/s]

## 3. Resultados oficiales y métricas

In [7]:
print("\n" + "="*50)
print(f"🏆 RESULTADOS OFICIALES EN TEST FIJO: {model_name}")
print("="*50)
print(f"F1-Score (Macro): {f1_score(y_true, y_pred, average='macro'):.4f}")
print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")
print("\nMatriz de Confusión:\n", confusion_matrix(y_true, y_pred))
print("\nClassification Report:\n", classification_report(y_true, y_pred, target_names=["No Misógino", "Misógino"]))

==================================================
🏆 RESULTADOS OFICIALES EN TEST FIJO: robertuito-base-uncased
==================================================
F1-Score (Macro): 0.6909
Accuracy: 0.6932

Matriz de Confusión:
 [[196  65]
 [ 89 152]]

Classification Report:
               precision    recall  f1-score   support

 No Misógino       0.69      0.75      0.72       261
    Misógino       0.70      0.63      0.66       241

    accuracy                           0.69       502
   macro avg       0.69      0.69      0.69       502
weighted avg       0.69      0.69      0.69       502

## 4. Guardado del CSV para futuro ensemble

In [8]:
ruta_guardado = f"{output_dir}/predicciones_test_{model_name}.csv"
pd.DataFrame(predicciones).to_csv(ruta_guardado, index=False)
print(f"\n✅ Archivo CSV de predicciones guardado en: {ruta_guardado}")

✅ Archivo CSV de predicciones guardado en: /content/drive/MyDrive/dataset/EXIST 2025 Videos Dataset/training/Research/Transformers/robertuito-base-uncased/predicciones_test_robertuito-base-uncased.csv